import { ShortCourse } from '../../src/types';

export const coursesPart2: ShortCourse[] = [
  // ----------------------------------------------------
  // CATEGORY 5: WEB & SOFTWARE DEVELOPMENT
  // ----------------------------------------------------
  {
    id: "sc-web-01",
    code: "AITI-WEB-001",
    title: "Web Design Fundamentals",
    slug: "web-design-fundamentals",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Learn how the modern web works: UI wireframing in Figma, responsive box models, typography, web color palettes, and creating your first HTML page.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Software Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Lead Full-Stack Software Engineer",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Web architecture (Clients, Servers, DNS, HTTP), browser developer tools",
      "Week 1: Figma prototyping: wireframing web landing pages and mobile responsive grids",
      "Week 2: Semantic HTML5 structure, links, images, tables, forms, and validation",
      "Week 2: Publishing your first live website on GitHub Pages and custom domains"
    ],
    learningObjectives: [
      "Design web page prototypes in Figma with mobile and desktop viewports",
      "Construct clean semantic HTML5 markup",
      "Deploy a live functional website to the public internet"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-web-02",
    code: "AITI-WEB-002",
    title: "HTML & CSS",
    slug: "html-css",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Master modern CSS3 styling: Flexbox layouts, CSS Grid systems, responsive media queries, CSS variables, pseudo-classes, animations, and Tailwind CSS basics.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Software Lab), AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Lead Full-Stack Engineer",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: CSS Box Model (Margins, Padding, Borders, Box-sizing), Selectors, and Specificity",
      "Week 1: Modern Layout Engines: CSS Flexbox in depth (align, justify, direction, wrap)",
      "Week 2: CSS Grid 2D layout systems, template columns, gap, and fractional units",
      "Week 2: Mobile-first responsive media queries and introduction to Tailwind CSS classes"
    ],
    learningObjectives: [
      "Build fully responsive web layouts that render flawlessly across mobile, tablet, and 4K screens",
      "Master CSS Flexbox and CSS Grid without layout breakage",
      "Accelerate styling workflows using utility-first CSS frameworks"
    ],
    entryRequirements: ["Basic HTML knowledge."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-web-03",
    code: "AITI-WEB-003",
    title: "JavaScript Fundamentals",
    slug: "javascript-fundamentals",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "The core programming language of the web: variables, data types, functions, DOM manipulation, event listeners, array methods, and async Fetch API.",
    duration: "3 Weeks",
    durationWeeks: 3,
    durationHours: 35,
    fee: 40000,
    feeGHS: 40000,
    trainingFee: 40000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-25",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Lead Software Engineer",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: JavaScript syntax, let/const, types, conditionals, loops, and arrow functions",
      "Week 2: Array iteration methods (map, filter, reduce, find) and Object destructuring",
      "Week 3: DOM selection, creating elements, event listeners, localStorage persistence",
      "Week 3: Asynchronous JS: Promises, async/await, fetching live REST API data (Weather/Currency)"
    ],
    learningObjectives: [
      "Add interactive behavior, dynamic modals, and calculators to web pages",
      "Manipulate HTML elements and process user input events dynamically",
      "Fetch real-time data from external APIs and render it asynchronously"
    ],
    entryRequirements: ["Basic HTML & CSS knowledge."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-web-04",
    code: "AITI-WEB-004",
    title: "Front-End Development",
    slug: "front-end-development",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Modern Single Page Application (SPA) development with React, TypeScript, Tailwind CSS, component state management, hooks, and client-side routing.",
    duration: "4 Weeks",
    durationWeeks: 4,
    durationHours: 50,
    fee: 50000,
    feeGHS: 50000,
    trainingFee: 50000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Software Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-10-02",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Senior Frontend Architect",
    availableSeats: 4,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 11,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Advanced",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: React basics: JSX, Components, Props, Vite tooling, and TypeScript types",
      "Week 2: React State & Hooks (useState, useEffect, useRef, useMemo), Form handling",
      "Week 3: Multi-page navigation with React Router, context API, and global state",
      "Week 4: Building a complete real-world e-commerce product catalog with shopping cart and checkout"
    ],
    learningObjectives: [
      "Build production-grade Single Page Web Applications in React and TypeScript",
      "Manage component state and asynchronous data lifecycles cleanly",
      "Assemble comprehensive frontend web projects ready for job applications"
    ],
    entryRequirements: ["Intermediate JavaScript proficiency."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-web-05",
    code: "AITI-WEB-005",
    title: "Back-End Development",
    slug: "back-end-development",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Build robust server-side APIs with Node.js, Express, RESTful routing, authentication (JWT), password hashing (bcrypt), and PostgreSQL database integration.",
    duration: "4 Weeks",
    durationWeeks: 4,
    durationHours: 50,
    fee: 50000,
    feeGHS: 50000,
    trainingFee: 50000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Software Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-10-02",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Lead Full-Stack Engineer",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Advanced",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Node.js runtime, NPM packages, Express server architecture, and middleware",
      "Week 2: RESTful API design: GET, POST, PUT, DELETE endpoints and input validation (Zod)",
      "Week 3: Database design: PostgreSQL / SQLite CRUD operations, connection pools, and ORM",
      "Week 4: User authentication: password hashing, JSON Web Tokens (JWT), role-based access, and deployment"
    ],
    learningObjectives: [
      "Architect secure, scalable RESTful API backends from scratch",
      "Implement user signup, login, password encryption, and token verification",
      "Deploy live backend web servers to cloud hosting providers"
    ],
    entryRequirements: ["Solid JavaScript foundations."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-web-06",
    code: "AITI-WEB-006",
    title: "WordPress Website Development",
    slug: "wordpress-website-development",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Launch professional corporate, school, church, blog, and e-commerce websites without coding: Elementor builder, WooCommerce, themes, plugins, and hosting.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Senior Web Developer",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Domain names, cPanel hosting setup, SSL certificates, and 1-click WordPress installation",
      "Week 1: Page builders: Elementor Pro visual editing, headers, footers, and responsive tablet/mobile tweaks",
      "Week 2: Essential plugins: Contact forms, SEO (Yoast/RankMath), caching, and security hardening",
      "Week 2: WooCommerce: Setting up an online store, adding products, Nigerian payment gateways (Paystack/Flutterwave)"
    ],
    learningObjectives: [
      "Build and launch complete commercial WordPress websites in 48 hours for paying clients",
      "Configure WooCommerce online shops with automated Paystack/Flutterwave debit card payments",
      "Manage client hosting cPanels, backups, and SSL certificates"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-web-07",
    code: "AITI-WEB-007",
    title: "Website Development with AI",
    slug: "website-development-with-ai",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Accelerate web development 10x using modern AI coding tools: Cursor AI editor, v0 by Vercel, Claude Code, GitHub Copilot, and automated component generation.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Alpha & Virtual Lab",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Full-Stack AI Developer",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Sep 28, 2026"],
    courseOutline: [
      "Configuring Cursor AI Editor: Command+K inline editing, codebase indexing, and composer",
      "v0.dev & Bolt.new: Generating full responsive UI components from natural language descriptions",
      "Prompting LLMs to write clean, bug-free TypeScript interfaces and SQL queries",
      "Debugging runtime web console errors and refactoring legacy code with AI",
      "Deploying AI-generated web apps to Vercel/Netlify with 1-click Git workflows"
    ],
    learningObjectives: [
      "Ship complete, production-ready web apps in 1/5th the traditional timeline",
      "Leverage AI code generation tools safely with manual verification checks",
      "Refactor and optimize slow or buggy code using AI code intelligence"
    ],
    entryRequirements: ["Basic HTML, CSS, or JS exposure."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-web-08",
    code: "AITI-WEB-008",
    title: "Programming Fundamentals",
    slug: "programming-fundamentals",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Learn computational thinking and algorithmic problem solving: variables, logic gates, branching, loops, data structures, recursion, and debugging.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Computer Science Faculty",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Algorithmic thinking: Flowcharts, pseudocode, and breaking problems into logical steps",
      "Week 1: Data types, memory allocation, variable declarations, and arithmetic/boolean operators",
      "Week 2: Control flow: IF/ELSE branching, SWITCH cases, FOR loops, and WHILE loops",
      "Week 2: Arrays, linear search, sorting algorithms, and step-by-step debugging"
    ],
    learningObjectives: [
      "Solve complex logic problems through structured algorithms and code",
      "Write bug-free control structures in any modern programming language",
      "Pass introductory technical coding interviews with confidence"
    ],
    entryRequirements: ["Open to beginners with an interest in coding."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-web-09",
    code: "AITI-WEB-009",
    title: "Introduction to Software Development",
    slug: "introduction-to-software-development",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "An orientation into the professional software engineering industry: SDLC, Agile/Scrum, version control, testing methodologies, DevOps, and career paths.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Zoom",
    venue: "Lab Alpha & Virtual Classroom",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "Lead Software Architect",
    availableSeats: 11,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 9,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Software Development Life Cycle (SDLC): Requirements, Design, Development, Testing, Deployment",
      "Agile Framework: Sprints, Daily Standups, Backlogs, User Stories, and Kanban Boards (Trello/Jira)",
      "Software Testing Basics: Unit Tests, Integration Tests, and QA Bug Reporting",
      "Cloud Hosting, Continuous Integration/Continuous Deployment (CI/CD) pipelines",
      "Software Engineering Career Tracks: Frontend, Backend, Fullstack, Mobile, DevOps, and QA"
    ],
    learningObjectives: [
      "Understand how modern engineering teams collaborate on large software codebases",
      "Participate effectively in Agile/Scrum project management ceremonies",
      "Chart a clear multi-year software engineering career roadmap"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-web-10",
    code: "AITI-WEB-010",
    title: "Git & GitHub Fundamentals",
    slug: "git-github-fundamentals",
    categoryId: "scc-5",
    categoryName: "Web & Software Development",
    category: "Web & Software Development",
    description: "Industry-standard version control: repositories, commits, branches, merge conflicts, pull requests, GitHub issues, and remote team collaboration.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "DevOps & Software Engineer",
    availableSeats: 9,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 6,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Sep 28, 2026"],
    courseOutline: [
      "Installing Git CLI, SSH Key configuration, and GitHub account setup",
      "Core Git workflow: git init, git status, git add, git commit -m, git log",
      "Branching strategies: git checkout -b, git branch, merging, and resolving merge conflicts",
      "Remote repositories: git push, git pull, git clone, and fork workflows",
      "Opening Pull Requests (PRs), code reviews, and hosting static projects on GitHub Pages"
    ],
    learningObjectives: [
      "Track codebase changes and roll back bugs safely with Git history",
      "Collaborate with international developer teams using Pull Requests on GitHub",
      "Maintain a green GitHub activity contribution chart to impress tech recruiters"
    ],
    entryRequirements: ["Basic coding familiarity."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },

  // ----------------------------------------------------
  // CATEGORY 6: DIGITAL MARKETING & BUSINESS
  // ----------------------------------------------------
  {
    id: "sc-mkt-01",
    code: "AITI-MKT-001",
    title: "Digital Marketing Fundamentals",
    slug: "digital-marketing-fundamentals",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "The complete foundation of digital marketing: buyer personas, sales funnels, paid vs organic traffic, conversion rate optimization, and digital campaign metrics.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Digital Growth Strategist",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: The Modern Digital Landscape: Inbound vs Outbound, Customer Journeys, and Touchpoints",
      "Week 1: Building High-Converting Sales Funnels: Top of Funnel (TOFU), MOFU, and BOFU",
      "Week 2: Traffic Channels: Search (SEO/SEM), Social Media, Email, Influencers, and WhatsApp",
      "Week 2: Key Metrics: Customer Acquisition Cost (CAC), Return on Ad Spend (ROAS), and Conversion Rates"
    ],
    learningObjectives: [
      "Map out profitable marketing funnels that convert cold prospects into paying clients",
      "Allocate digital advertising budgets effectively across multiple channels",
      "Measure and report digital marketing ROI accurately"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-mkt-02",
    code: "AITI-MKT-002",
    title: "Social Media Management",
    slug: "social-media-management",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Manage brand social channels like a pro: content calendars, community management, brand tone of voice, scheduling tools (Buffer/Meta Business Suite), and analytics.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Social Media Director",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Developing a Monthly Content Calendar and 30-day content pillars",
      "Week 1: Meta Business Suite: scheduling automated posts across Facebook & Instagram simultaneously",
      "Week 2: Community engagement: handling DMs, crisis communications, negative comments, and customer reviews",
      "Week 2: Social media audit reports: calculating engagement rates, follower growth velocity, and reach"
    ],
    learningObjectives: [
      "Manage social media business pages on monthly client retainers",
      "Schedule 30 days of automated content across multiple platforms in one sitting",
      "Deliver professional monthly performance analytical reports to business clients"
    ],
    entryRequirements: ["Active on social media platforms."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-mkt-03",
    code: "AITI-MKT-003",
    title: "Social Media Marketing",
    slug: "social-media-marketing",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Drive exponential organic and paid growth on Instagram, TikTok, LinkedIn, and X: viral algorithms, influencer collaborations, user-generated content, and growth hacking.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Digital Growth Strategist",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Mastering platform algorithms: Instagram Reels, TikTok FYP, LinkedIn thought leadership",
      "Week 1: Influencer marketing: scouting nano/micro influencers, contract negotiation, and ROI tracking",
      "Week 2: User Generated Content (UGC) campaigns and viral giveaways that build massive email lists",
      "Week 2: Social selling in DMs: converting warm inquiries into closed phone consultations and sales"
    ],
    learningObjectives: [
      "Grow targeted follower bases using algorithmic video hooks and trends",
      "Structure profitable micro-influencer campaigns on tight budgets",
      "Convert social media followers directly into high-ticket buyers"
    ],
    entryRequirements: ["Basic smartphone or computer usage."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-mkt-04",
    code: "AITI-MKT-004",
    title: "Facebook & Instagram Marketing",
    slug: "facebook-instagram-marketing",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Master Meta Ads Manager: detailed audience targeting, custom audiences, lookalikes, Meta Pixel installation, A/B creative testing, and scaling profitable ad spend.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Paid Media Specialist",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Meta Ads Manager structure: Campaign Objectives (Traffic, Leads, Sales), Ad Sets, and Ads",
      "Week 1: Detailed demographic, interest, and geographic targeting in Nigeria and international markets",
      "Week 2: Meta Pixel and Conversions API setup, event tracking (Add to Cart, Purchase, Lead)",
      "Week 2: Retargeting custom audiences, Lookalike audiences (1%-5%), and ad budget scaling techniques"
    ],
    learningObjectives: [
      "Launch profitable sponsored ad campaigns with predictable Cost Per Lead (CPL)",
      "Retarget past website visitors and video viewers to recover lost sales",
      "Avoid common ad account bans by complying strictly with Meta advertising policies"
    ],
    entryRequirements: ["A Facebook profile and payment card."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-mkt-05",
    code: "AITI-MKT-005",
    title: "Content Creation",
    slug: "content-creation",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Write and shoot high-converting digital content: copywriting psychology, video hooks, storytelling, carousel design, podcasting basics, and personal brand building.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Content Strategist",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: The Psychology of Attention: 3-second hooks, open loops, curiosity gaps, and emotional triggers",
      "Week 1: Writing persuasive long-form captions, email newsletters, and Twitter/X threads",
      "Week 2: Smartphone video shooting: ring lights, lapel microphones, framing, and teleprompter apps",
      "Week 2: Repurposing 1 long video into 10 bite-sized TikToks, Reels, carousels, and quotes"
    ],
    learningObjectives: [
      "Craft irresistible video and written hooks that stop audience scrolling immediately",
      "Shoot crisp, high-audio-quality smartphone videos without expensive studio gear",
      "Build an efficient 1-to-many multi-platform content repurposing engine"
    ],
    entryRequirements: ["Smartphone with camera."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-mkt-06",
    code: "AITI-MKT-006",
    title: "WhatsApp Business Marketing",
    slug: "whatsapp-business-marketing",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Monetize Africa's #1 communication app: WhatsApp Catalog, automated quick replies, Broadcast lists, Status marketing strategies, chatbots, and CRM integrations.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "WhatsApp Commerce Consultant",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "WhatsApp Business app optimization: Business profile, catalog items, pricing, and greeting messages",
      "Generating 500+ daily WhatsApp contacts via Lead Generation ads and landing page links (wa.link)",
      "WhatsApp Status marketing: storytelling frameworks, flash sales, and driving high viewer retention",
      "Broadcast list etiquette without getting banned and contact tagging with labels",
      "WhatsApp Cloud API & Auto-responder chatbots for 24/7 automated customer order handling"
    ],
    learningObjectives: [
      "Turn your personal WhatsApp into a daily cash-generating sales storefront",
      "Collect and manage hundreds of qualified customer phone contacts systematically",
      "Deploy automated auto-reply bots that answer inquiries and take orders while you sleep"
    ],
    entryRequirements: ["Smartphone with WhatsApp Business."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-mkt-07",
    code: "AITI-MKT-007",
    title: "Search Engine Optimization",
    slug: "search-engine-optimization",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Rank #1 on Google organically: Keyword research, on-page SEO, technical site speed audits, high-authority backlink building, and Google Search Console.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Alpha & Virtual Lab",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "SEO & Growth Specialist",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: How Google Search works: Crawling, Indexing, and Ranking algorithms",
      "Week 1: Keyword Research: Finding high-intent, low-competition search queries with Semrush/Ubersuggest",
      "Week 2: On-Page SEO: Title tags, Meta descriptions, Header hierarchy, Alt text, and Internal links",
      "Week 2: Technical SEO & Google Search Console: XML sitemaps, Core Web Vitals, and Local SEO (Google Business Profile)"
    ],
    learningObjectives: [
      "Rank local and international business websites on the first page of Google",
      "Drive sustainable, free organic customer traffic without paying for ads",
      "Optimize Google Business Profiles to dominate local map pack searches"
    ],
    entryRequirements: ["Basic web navigation."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-mkt-08",
    code: "AITI-MKT-008",
    title: "Online Business Setup",
    slug: "online-business-setup",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Launch your internet business from scratch: niche selection, CAC registration guidelines, domain & email branding, digital payment gateways, and client contracts.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Mr. S. A. Adeleke",
    instructorName: "Mr. S. A. Adeleke",
    instructorTitle: "Business Development Consultant",
    availableSeats: 10,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 5,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Identifying high-demand digital services: consulting, freelancing, e-commerce, and agency services",
      "Corporate affairs readiness: Business name registration, TIN tax identification, and corporate bank accounts",
      "Setting up official domain email addresses (e.g. info@yourcompany.com) with Google Workspace",
      "Integrating Paystack, Flutterwave, and USD virtual accounts (Geegpay/Grey) for global payments",
      "Client onboarding workflows: proposals, professional invoices, receipts, and service agreements"
    ],
    learningObjectives: [
      "Establish a legitimate, legally registered online business structure in 7 days",
      "Accept payments in Nigerian Naira (₦) and international foreign currencies (USD/GBP)",
      "Present corporate credibility to win high-paying business contracts"
    ],
    entryRequirements: ["Entrepreneurs, freelancers, and aspiring business owners."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-mkt-09",
    code: "AITI-MKT-009",
    title: "Digital Branding",
    slug: "digital-branding",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Position your brand as the premium authority in your industry: brand story, value propositions, online reputation management, and visual consistency across all digital touchpoints.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Brand Strategist",
    availableSeats: 9,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 11,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Defining your Unique Selling Proposition (USP) and brand positioning statement",
      "Crafting an emotional founder brand story that fosters deep customer loyalty",
      "Auditing digital brand consistency across websites, social handles, email signatures, and invoices",
      "Online reputation management: collecting 5-star Google reviews and handling PR issues",
      "Building a high-authority personal brand on LinkedIn and industry blogs"
    ],
    learningObjectives: [
      "Charge higher premium prices by commanding exceptional digital brand perceived value",
      "Standardize brand touchpoints to look like an established multi-million naira enterprise",
      "Build an unshakeable online reputation that generates unsolicited word-of-mouth referrals"
    ],
    entryRequirements: ["Business owners and professionals."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-mkt-10",
    code: "AITI-MKT-010",
    title: "E-commerce Fundamentals",
    slug: "e-commerce-fundamentals",
    categoryId: "scc-6",
    categoryName: "Digital Marketing & Business",
    category: "Digital Marketing & Business",
    description: "Launch and scale physical product e-commerce in Nigeria: product sourcing, Shopify/WooCommerce setup, logistics delivery partnerships (GIG/Waybill), and COD cash flow.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. S. A. Adeleke",
    instructorName: "Mr. S. A. Adeleke",
    instructorTitle: "E-commerce & Logistics Consultant",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Winning product research criteria, local market sourcing, and margin calculations",
      "Week 1: Building a high-converting one-product sales funnel page with Paystack payment gateway",
      "Week 2: Logistics in Nigeria: 3PL delivery partners, state riders, handling Cash on Delivery (COD)",
      "Week 2: Order confirmation customer call center scripts and reducing delivery cancellation rates"
    ],
    learningObjectives: [
      "Source and launch profitable e-commerce products with 50%+ net profit margins",
      "Build frictionless one-page checkout landing pages that convert cold ad traffic",
      "Structure reliable interstate logistics networks across all 36 Nigerian states"
    ],
    entryRequirements: ["Basic internet literacy."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },

  // ----------------------------------------------------
  // CATEGORY 7: VIDEO & DIGITAL MEDIA
  // ----------------------------------------------------
  {
    id: "sc-vid-01",
    code: "AITI-VID-001",
    title: "Video Editing",
    slug: "video-editing",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "Foundations of digital video editing: timeline slicing, transitions, B-roll overlays, audio sync, sound effects, background music mixing, and exporting high-res MP4s.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Media Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Video Producer & Editor",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Video file codecs (.mp4, .mov, ProRes), frame rates (24fps vs 60fps), and project setup",
      "Week 1: Cutting on action, J-cuts, L-cuts, speed ramps, and seamless visual transitions",
      "Week 2: Audio cleanup: background noise removal, equalization, sound effects (SFX), and volume ducking",
      "Week 2: Color correction, contrast balancing, basic LUT grading, and YouTube/Instagram render presets"
    ],
    learningObjectives: [
      "Edit smooth, professionally paced video stories from raw footage",
      "Clean up noisy audio recordings and balance background music levels",
      "Export crisp, correctly compressed videos for YouTube, TikTok, and corporate clients"
    ],
    entryRequirements: ["Basic computer familiarity."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-vid-02",
    code: "AITI-VID-002",
    title: "CapCut Video Editing",
    slug: "capcut-video-editing",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "Master CapCut for PC and Mobile: animated text captions, keyframes, sound design, auto-captions, viral effects, green screen removal, and trending templates.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Short-Form Video Specialist",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Sep 28, 2026"],
    courseOutline: [
      "CapCut Desktop & Mobile interface, aspect ratio presets (9:16 vertical vs 16:9 widescreen)",
      "Auto-captions: customizing animated karaoke text, font styling, and highlighted keywords",
      "Keyframe animations: zooming into points of interest, panning across photos, and pop-up stickers",
      "Green screen chroma keying, background removal, and speed ramping for dynamic pacing",
      "Sound design: adding whooshes, cash register sounds, trending TikTok audio, and 4K exports"
    ],
    learningObjectives: [
      "Edit viral, professional-quality TikTok and Instagram Reels in under 20 minutes",
      "Generate dynamic, perfectly timed animated subtitles with highlighted keywords",
      "Produce engaging short-form video ads for businesses and personal brands"
    ],
    entryRequirements: ["Smartphone or laptop."],
    scheduleDetails: "Monday to Friday: 1:30 PM - 4:30 PM"
  },
  {
    id: "sc-vid-03",
    code: "AITI-VID-003",
    title: "Professional Video Editing",
    slug: "professional-video-editing",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "Industry-grade post-production in Adobe Premiere Pro & DaVinci Resolve: multi-camera editing, advanced color grading, motion graphics titles, and cinema exports.",
    duration: "4 Weeks",
    durationWeeks: 4,
    durationHours: 50,
    fee: 50000,
    feeGHS: 50000,
    trainingFee: 50000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Media Production Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-10-02",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Lead Video Producer",
    availableSeats: 4,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Advanced",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Premiere Pro workspace, proxy workflows for 4K footage, rough cuts, and assembly",
      "Week 2: Multi-cam synchronization for wedding coverage, church services, and talk shows",
      "Week 3: DaVinci Resolve color page: primary color wheels, curves, skin tone vectorscopes, and film LUTs",
      "Week 4: Essential Graphics: animated lower thirds, title openers, audio mastering, and DCP/Broadcast delivery"
    ],
    learningObjectives: [
      "Edit full-length documentaries, music videos, wedding films, and corporate commercials",
      "Grade cinema-grade colors matching Hollywood and Nollywood production standards",
      "Master multi-camera live switching and audio stem mastering"
    ],
    entryRequirements: ["Basic computer and video editing exposure."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-vid-04",
    code: "AITI-VID-004",
    title: "YouTube Content Creation",
    slug: "youtube-content-creation",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "Build a profitable YouTube channel: channel branding, high-CTR thumbnail design, video scripting, studio lighting, SEO tags, and YouTube Partner monetization.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "YouTube Creator & Producer",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Channel niche validation, competitor analysis, banner art, and channel branding",
      "Week 1: Scripting for viewer retention: 30-second hooks, pacing, and storytelling arcs",
      "Week 2: Designing high-CTR thumbnails (Photoshop) and crafting click-worthy video titles",
      "Week 2: YouTube Analytics deep dive: Click-Through Rate (CTR), Average Percentage Viewed (APV), and monetization"
    ],
    learningObjectives: [
      "Launch a fully optimized, branded YouTube channel capable of algorithmic growth",
      "Design 15%+ CTR thumbnails that attract thousands of organic views",
      "Monetize your channel through Google AdSense, sponsorships, and digital products"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-vid-05",
    code: "AITI-VID-005",
    title: "Social Media Video Production",
    slug: "social-media-video-production",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "Produce short-form vertical video content for TikTok, Instagram Reels, and YouTube Shorts: lighting, audio, framing, teleprompter delivery, and batch recording.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Media Studio), AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Media Production Specialist",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Lighting setups on a budget: key light, fill light, rim light, and RGB tube background accents",
      "Wireless lapel microphones (DJI/Rode/BoyA) and achieving broadcast-quality audio",
      "Camera presence, confident eye contact, body language, and teleprompter reading fluency",
      "Batch shooting: recording 15 viral video scripts in a single 3-hour studio session",
      "Optimizing video metadata, captions, sound selection, and hashtag strategies for TikTok/Reels"
    ],
    learningObjectives: [
      "Speak on camera with natural charisma and authority without stammering",
      "Set up an attractive mini-studio space in your home or office",
      "Batch-produce weeks of short video content rapidly"
    ],
    entryRequirements: ["Smartphone with camera."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-vid-06",
    code: "AITI-VID-006",
    title: "Photography Fundamentals",
    slug: "photography-fundamentals",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "Master manual DSLR/Mirrorless camera controls: Aperture (f-stop), Shutter Speed, ISO exposure triangle, lens choices, portrait lighting, and Lightroom editing.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Photo Studio), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Lead Photographer & Studio Director",
    availableSeats: 6,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 6,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: The Exposure Triangle: Aperture (depth of field), Shutter Speed (motion blur), ISO (noise)",
      "Week 1: Lens characteristics: Prime 50mm/85mm for portraits vs Wide 24mm vs Telephoto 70-200mm",
      "Week 2: Studio flash lighting: Speedlights, softboxes, beauty dishes, reflectors, and outdoor golden hour",
      "Week 2: Adobe Lightroom Classic: RAW image import, color grading presets, skin tones, and high-res exports"
    ],
    learningObjectives: [
      "Shoot in full manual camera mode under any lighting condition without blurry photos",
      "Create beautiful blurred background bokeh portraits with professional depth",
      "Batch-edit hundreds of event photography RAW files in Adobe Lightroom"
    ],
    entryRequirements: ["DSLR, mirrorless camera, or pro-mode smartphone."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-vid-07",
    code: "AITI-VID-007",
    title: "Digital Content Creation",
    slug: "digital-content-creation",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "An integrated media creator boot camp: photography, video, graphic carousels, audio recording, and copywriting combined into a complete creator skill set.",
    duration: "3 Weeks",
    durationWeeks: 3,
    durationHours: 35,
    fee: 40000,
    feeGHS: 40000,
    trainingFee: 40000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Media Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Creative Director",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Visual identity, graphic design (Canva/Photoshop), and slide deck carousels",
      "Week 2: Smartphone/DSLR video production, cinematic B-roll filming, and CapCut/Premiere editing",
      "Week 3: Audio podcasting, voiceovers, multi-channel distribution, and building a monetization funnel"
    ],
    learningObjectives: [
      "Operate as a full-stack solo digital content agency for businesses or your own personal brand",
      "Produce photos, graphics, videos, and podcasts at commercial broadcast standards",
      "Build a portfolio that attracts brand sponsorships and client content retainers"
    ],
    entryRequirements: ["Basic computer or smartphone literacy."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-vid-08",
    code: "AITI-VID-008",
    title: "Live Streaming",
    slug: "live-streaming",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "Broadcast live church services, conferences, concerts, and e-learning lectures using OBS Studio, vMix, multi-camera switchers (ATEM Mini), and Restream.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Broadcast & Stream Suite), AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Broadcast & IT Engineer",
    availableSeats: 6,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 6,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: OBS Studio setup: Scenes, Sources, Audio Mixer, Bitrate encoding, and RTMP stream keys",
      "Week 1: Video capture cards (Cam Link), HDMI switchers (Blackmagic ATEM Mini), and PTZ cameras",
      "Week 2: Multistreaming simultaneously to YouTube, Facebook, and Zoom using Restream.io",
      "Week 2: Live lower third titles, lyrics overlays, audio mixing console integration, and backup internet failover"
    ],
    learningObjectives: [
      "Manage professional live broadcast productions for churches, corporate events, and conferences",
      "Stream multi-camera productions to YouTube and Facebook in full 1080p60 without buffering",
      "Integrate live worship lyrics, speaker lower thirds, and pre-recorded video playouts"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-vid-09",
    code: "AITI-VID-009",
    title: "Multimedia Production",
    slug: "multimedia-production",
    categoryId: "scc-7",
    categoryName: "Video & Digital Media",
    category: "Video & Digital Media",
    description: "An intensive comprehensive program combining 2D motion graphics (After Effects), audio production, digital video recording, and commercial advert production.",
    duration: "4 Weeks",
    durationWeeks: 4,
    durationHours: 50,
    fee: 50000,
    feeGHS: 50000,
    trainingFee: 50000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Media Production Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-10-02",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Multimedia Production Faculty Lead",
    availableSeats: 4,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Advanced",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Digital photography, studio lighting, and high-resolution photo composition",
      "Week 2: Video cinematography, framing, audio recording, and Premiere Pro video editing",
      "Week 3: Adobe After Effects: 2D animation, animated typography, logo reveals, and motion graphics",
      "Week 4: Final Commercial Production: Scripting, shooting, editing, and packaging a 60-second corporate TV/Web ad"
    ],
    learningObjectives: [
      "Direct and execute complete multimedia advertising campaigns from storyboard to final render",
      "Create kinetic typography and animated 2D logo intros in Adobe After Effects",
      "Qualify for multimedia producer roles in television, advertising, and corporate media houses"
    ],
    entryRequirements: ["Basic computer usage and visual interest."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },

  // ----------------------------------------------------
  // CATEGORY 8: COMPUTER HARDWARE & NETWORKING
  // ----------------------------------------------------
  {
    id: "sc-hw-01",
    code: "AITI-HW-001",
    title: "Computer Hardware Fundamentals",
    slug: "computer-hardware-fundamentals",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Understand the anatomy of desktop and laptop computers: Motherboards, CPUs, RAM types (DDR4/DDR5), Power Supplies (PSU), SATA/NVMe SSDs, and system buses.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Hardware Engineering Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Lead IT Infrastructure Engineer",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Safety protocols (ESD static protection) and tools (multimeters, anti-static wristbands)",
      "Week 1: Disassembling desktop PCs: identifying processors, sockets, chipsets, RAM slots, and PCIe expansion slots",
      "Week 2: Power supply calculations, 12V rails, SATA vs PCIe NVMe M.2 SSD storage architecture",
      "Week 2: Reassembling a custom PC from loose components, cable management, and BIOS POST testing"
    ],
    learningObjectives: [
      "Identify every internal electronic component and port in modern desktop and laptop systems",
      "Assemble desktop PCs from individual components safely without ESD damage",
      "Configure motherboard BIOS/UEFI boot priority settings"
    ],
    entryRequirements: ["No prior hardware experience required."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-hw-02",
    code: "AITI-HW-002",
    title: "Computer Repairs",
    slug: "computer-repairs",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Diagnose and fix faulty desktop computers: no-power faults, continuous beeping codes, Blue Screen of Death (BSOD), overheating, and bad power supplies.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Hardware Engineering Lab), AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Hardware Maintenance Engineer",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Hardware diagnostic methodology: Isolate power, RAM, processor, or motherboard failures",
      "Week 1: Motherboard POST beep code interpretation and diagnostic testing cards",
      "Week 2: Power supply testing with digital multimeters, replacing faulty cooling fans and thermal paste",
      "Week 2: Memory (RAM) testing with MemTest86, bad sector repair on HDDs, and cloning drives to SSD"
    ],
    learningObjectives: [
      "Troubleshoot non-booting or freezing desktop PCs using systematic diagnostic steps",
      "Use multimeters to verify voltage rails on motherboards and power supplies",
      "Recover client data and clone failing spinning hard drives to high-speed SSDs"
    ],
    entryRequirements: ["Basic computer hardware awareness."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-hw-03",
    code: "AITI-HW-003",
    title: "Laptop Repairs",
    slug: "laptop-repairs",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Hands-on laptop disassembly, screen replacement, keyboard repair, battery replacement, thermal fan servicing, charging port fixing, and hinge rebuilding.",
    duration: "3 Weeks",
    durationWeeks: 3,
    durationHours: 35,
    fee: 40000,
    feeGHS: 40000,
    trainingFee: 40000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Hardware Engineering Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Lead Hardware Engineer",
    availableSeats: 4,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Advanced",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Precision laptop opening techniques (HP, Dell, Lenovo, MacBook) without breaking plastic clips",
      "Week 2: Broken LCD/LED screen replacement, 30-pin vs 40-pin eDP display cables, and bezel fitting",
      "Week 3: Replacing internal laptop batteries, DC charging jacks, internal keyboards, trackpads, and broken hinges"
    ],
    learningObjectives: [
      "Disassemble and reassemble major laptop brands safely and cleanly",
      "Replace broken laptop screens, keyboards, and internal batteries",
      "Repair cracked laptop hinges using industrial resin bonding techniques"
    ],
    entryRequirements: ["Basic hardware repair familiarity."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-hw-04",
    code: "AITI-HW-004",
    title: "Computer Maintenance",
    slug: "computer-maintenance",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Preventive maintenance protocols for schools, cybercafes, and offices: dust blowing, thermal repasting, OS optimization, disk health monitoring, and system upgrades.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Systems Maintenance Engineer",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Physical maintenance: Air blower dust extraction, cleaning heatsinks, and fan lubrication",
      "Thermal maintenance: Cleaning old degraded paste and applying high-conductivity thermal compound",
      "Software tune-up: Disabling startup bloatware, registry cleanup, temp file deletion, and disk defragmentation",
      "Storage health checks: SMART drive status monitoring (CrystalDiskInfo) to prevent sudden data loss",
      "Designing quarterly IT maintenance service contract checklists for corporate clients"
    ],
    learningObjectives: [
      "Extend the operational lifespan of company computer workstations by years",
      "Prevent catastrophic overheating and thermal throttling shutdowns",
      "Offer lucrative recurring quarterly IT maintenance contracts to corporate offices"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-hw-05",
    code: "AITI-HW-005",
    title: "Windows Installation & Configuration",
    slug: "windows-installation-configuration",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Create bootable USB flash drives (Rufus/Ventoy), perform clean Windows 10/11 installations, partition disks (GPT/MBR), install official device drivers, and configure user accounts.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Systems Administrator",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Sep 28, 2026"],
    courseOutline: [
      "Creating multi-boot installation USB flash drives using Rufus and Ventoy with Windows 10 & 11 ISOs",
      "BIOS vs UEFI, Secure Boot, TPM 2.0 requirements, and disk partitioning (MBR vs GPT)",
      "Clean Windows installation walkthrough, bypass network prompts, and creating local admin accounts",
      "Hardware driver installation: Chipset, Graphics (Nvidia/Intel), Audio, Wi-Fi, and Bluetooth",
      "System activation, essential software packages, and creating system restore points"
    ],
    learningObjectives: [
      "Install official Windows operating systems on any brand of laptop or desktop",
      "Resolve missing driver errors in Windows Device Manager",
      "Configure fast, clutter-free Windows workstations ready for office deployment"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Friday: 1:30 PM - 4:30 PM"
  },
  {
    id: "sc-hw-06",
    code: "AITI-HW-006",
    title: "Software Installation & Troubleshooting",
    slug: "software-installation-troubleshooting",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Install, configure, and troubleshoot professional software suites: Microsoft Office, Adobe Creative Cloud, AutoCAD, CorelDRAW, antivirus, and fix DLL missing errors.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Systems Support Specialist",
    availableSeats: 9,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 6,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Standard software installation procedures, license activation, and silent install parameters",
      "Installing heavy design software (AutoCAD, Adobe Master Suite, CorelDRAW) without crashes",
      "Troubleshooting common runtime errors: Missing DLL files, .NET Framework, and Visual C++ Redistributables",
      "Malware, spyware, and ransomware removal using specialized bootable rescue USBs",
      "Remote technical support setup using AnyDesk, TeamViewer, and Windows Quick Assist"
    ],
    learningObjectives: [
      "Resolve stubborn Windows application crashes and missing library errors",
      "Clean deeply infected computer systems of malware and adware",
      "Provide remote IT software support to clients anywhere in the world"
    ],
    entryRequirements: ["Basic computer knowledge."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-hw-07",
    code: "AITI-HW-007",
    title: "Computer Networking Fundamentals",
    slug: "computer-networking-fundamentals",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Core networking principles: OSI model, TCP/IP, IPv4 addressing, subnet masks, default gateways, DNS resolution, DHCP servers, and network topologies.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Networking Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Lead IT Infrastructure Engineer",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: The 7 Layers of the OSI Model and TCP/IP protocol suite comparison",
      "Week 1: IPv4 Addressing: Class A, B, C, Private vs Public IPs, and Subnetting (/24, /28) calculations",
      "Week 2: Network services: Domain Name System (DNS), DHCP automated IP leasing, and Default Gateway routing",
      "Week 2: Command line network diagnostics: ping, ipconfig /all, tracert, nslookup, and netstat"
    ],
    learningObjectives: [
      "Understand how data packets traverse Local Area Networks and the global internet",
      "Assign static IP addresses and configure DHCP scope pools on office routers",
      "Diagnose connectivity drops quickly using standard command line tools"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-hw-08",
    code: "AITI-HW-008",
    title: "Network Installation",
    slug: "network-installation",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Hands-on physical network deployment: Cat6 Ethernet cabling, RJ45 crimping (T568A/B), punch down keystones, patch panels, switch trunking, and Wi-Fi access points.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Networking Suite), AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Lead Network Infrastructure Engineer",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Cat6 UTP cabling, stripping, color coding (T568B standard), RJ45 crimping, and cable tester verification",
      "Week 1: Terminating network wall jacks (RJ45 Keystones) using punch-down tools and surface mount faceplates",
      "Week 2: Setting up server racks: Patch panels, unmanaged vs managed switches, and cable management combs",
      "Week 2: Configuring enterprise Wi-Fi Access Points (Ubiquiti UniFi/MikroTik), SSIDs, VLANs, and captive portals"
    ],
    learningObjectives: [
      "Crimp and test faultless Cat6 patch cords and structured building network drops",
      "Assemble and wire clean server racks and patch panels for corporate offices",
      "Deploy seamless enterprise Wi-Fi networks with guest isolation and bandwidth controls"
    ],
    entryRequirements: ["Basic networking knowledge."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-hw-09",
    code: "AITI-HW-009",
    title: "CCTV Installation Fundamentals",
    slug: "cctv-installation-fundamentals",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Install and configure modern security surveillance: Analog HD vs IP PoE cameras, NVR/DVR setup, hard drive recording calculations, mobile phone live remote viewing.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Security Systems Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Security Systems Engineer",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Camera types: Dome vs Bullet vs PTZ cameras, focal lengths (2.8mm wide vs 4mm vs 6mm)",
      "Week 1: Coaxial BNC cabling with DC power vs IP PoE (Power over Ethernet) Cat6 network cameras",
      "Week 2: Configuring NVR/DVR: motion detection zones, recording schedules, and storage capacity planning",
      "Week 2: Network port forwarding, P2P cloud setup, and configuring smartphone live viewing apps (Hik-Connect / DMSS)"
    ],
    learningObjectives: [
      "Install residential and commercial CCTV camera security systems from start to finish",
      "Connect NVR/DVRs to the internet for live worldwide remote viewing on smartphones",
      "Configure automated motion detection alerts and continuous night vision recording"
    ],
    entryRequirements: ["Basic computer or electrical interest."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-hw-10",
    code: "AITI-HW-010",
    title: "Basic IT Support",
    slug: "basic-it-support",
    categoryId: "scc-8",
    categoryName: "Computer Hardware & Networking",
    category: "Computer Hardware & Networking",
    description: "Launch your career as a Helpdesk / IT Support Officer: user onboarding, printer networking, password resets, ticketing systems, asset tracking, and customer service.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Lead IT Infrastructure Engineer",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: IT Helpdesk workflow: SLA response times, ticketing platforms (Freshdesk/Zendesk), and phone etiquette",
      "Week 1: Connecting and sharing network printers, paper jam troubleshooting, and toner replacements",
      "Week 2: User account provisioning in Microsoft 365, password resets, and email client setup",
      "Week 2: Hardware inventory asset tagging, warranty logs, and IT escalation documentation"
    ],
    learningObjectives: [
      "Qualify for Tier-1 IT Support Specialist and Helpdesk Technician job openings",
      "Troubleshoot networked office multi-function printers and scanner sharing",
      "Manage support tickets with professional customer service composure"
    ],
    entryRequirements: ["Basic computer hardware and software familiarity."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  }
];
