import { ShortCourse } from '../../src/types';

export const coursesPart1: ShortCourse[] = [
  // 1. ICT & COMPUTER FUNDAMENTALS
  {
    id: "sc-ict-01",
    code: "AITI-ICT-001",
    title: "Computer Appreciation",
    slug: "computer-appreciation",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "A friendly and practical beginner course covering computer basics, hardware identification, Windows navigation, mouse & keyboard fluency, and basic troubleshooting.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Workstation Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-11",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Senior ICT Instructor",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Sep 21, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Introduction to computer anatomy: CPU, Monitor, Keyboard, Mouse, and Peripherals",
      "Powering On/Off safely and understanding the Windows 11 Desktop environment",
      "Keyboard mastery, special keys, touch navigation, and mouse clicking/drag techniques",
      "Launching applications, window controls (minimize, maximize, close), and multitasking",
      "Safe shutdown procedures, storage flash drives, and basic preventive care"
    ],
    learningObjectives: [
      "Operate a personal computer independently with confidence",
      "Navigate operating system menus, taskbars, and system settings",
      "Utilize peripheral devices such as flash drives, printers, and headphones"
    ],
    entryRequirements: ["No prior computer knowledge required. Open to all ages and backgrounds."],
    scheduleDetails: "Monday to Friday: 9:00 AM - 12:00 PM"
  },
  {
    id: "sc-ict-02",
    code: "AITI-ICT-002",
    title: "ICT Fundamentals",
    slug: "ict-fundamentals",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Core digital literacy covering computing concepts, modern digital devices, software installation, cloud basics, and foundational IT skills.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 30,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Lead IT Infrastructure Engineer",
    availableSeats: 10,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 5,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Computer architecture, system software vs application software",
      "Week 1: Operating system configuration, personalization, and driver checks",
      "Week 2: Internet connectivity, browsers, search engine mechanics, and cloud drives",
      "Week 2: Essential software utilities: PDF readers, compression tools, and antivirus"
    ],
    learningObjectives: [
      "Understand core computing hardware, memory types, and software layers",
      "Install and configure standard desktop productivity software",
      "Utilize cloud storage services for seamless document backups"
    ],
    entryRequirements: ["Basic willingness to learn digital technology."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-ict-03",
    code: "AITI-ICT-003",
    title: "Microsoft Word",
    slug: "microsoft-word",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Hands-on word processing mastery: typing, executive formatting, tables, graphics, official headers/footers, mail merge, and PDF publishing.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Zoom",
    venue: "Lab Beta / Online Live Stream",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Senior Office Automation Lead",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Sep 28, 2026"],
    courseOutline: [
      "Document creation, typography, paragraph alignment, line spacing, and indentation",
      "Page layout, margins, orientation, multi-column setups, and page borders",
      "Tables, cell merging, styling, and inserting pictures, icons & shapes",
      "Headers, footers, automated page numbers, and custom cover pages",
      "Mail Merge for mass letters, labels, certificates, and export to PDF"
    ],
    learningObjectives: [
      "Format official corporate correspondence and administrative documents",
      "Execute automated Mail Merge workflows for bulk correspondence",
      "Produce publication-ready reports with tables and visual diagrams"
    ],
    entryRequirements: ["Basic keyboard and mouse familiarity."],
    scheduleDetails: "Monday to Friday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-ict-04",
    code: "AITI-ICT-004",
    title: "Microsoft Excel",
    slug: "microsoft-excel",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Fundamental spreadsheet skills covering grid navigation, data entry, cell formatting, basic mathematical formulas (SUM, AVERAGE, COUNT), and simple charts.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. S. A. Adeleke",
    instructorName: "Mr. S. A. Adeleke",
    instructorTitle: "Spreadsheet & Financial Systems Specialist",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Sep 21, 2026"],
    courseOutline: [
      "Week 1: Excel interface, rows, columns, cells, data types, and autofill series",
      "Week 1: Basic arithmetic operators, SUM, AVERAGE, MIN, MAX, COUNT formulas",
      "Week 2: Cell referencing (Relative vs Absolute $), formatting numbers and currency",
      "Week 2: Sorting, filtering lists, creating Column/Bar/Pie charts, and print setup"
    ],
    learningObjectives: [
      "Construct well-organized tabular budgets, price lists, and inventory sheets",
      "Apply foundational arithmetic and statistical formulas without errors",
      "Generate clean visual charts to illustrate data trends"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-ict-05",
    code: "AITI-ICT-005",
    title: "Microsoft PowerPoint",
    slug: "microsoft-powerpoint",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Design compelling slide decks, pitch presentations, lectures, and corporate reports using layouts, transitions, animations, SmartArt, and speaker notes.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Senior Administrative Tech Specialist",
    availableSeats: 9,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 6,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Slide layout selection, typography hierarchy, and master slide themes",
      "Inserting visual assets: high-res photos, icons, shapes, and SmartArt diagrams",
      "Transitions vs Animations: best practices for professional slide pacing",
      "Embedding video, audio clips, charts, and interactive hyperlinks",
      "Presenter View, slide timings, pointer tools, and exporting to PDF/video"
    ],
    learningObjectives: [
      "Craft modern, clutter-free presentations for business, academic, or church audiences",
      "Use SmartArt to translate complex processes into easy-to-read graphics",
      "Deliver smooth live presentations with confidence using Presenter View"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Friday: 1:30 PM - 4:30 PM"
  },
  {
    id: "sc-ict-06",
    code: "AITI-ICT-006",
    title: "Microsoft Office Complete",
    slug: "microsoft-office-complete",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "An all-in-one comprehensive intensive program covering Word, Excel, PowerPoint, Outlook, and OneDrive integration for full digital workplace readiness.",
    duration: "4 Weeks",
    durationWeeks: 4,
    durationHours: 50,
    fee: 45000,
    feeGHS: 45000,
    trainingFee: 45000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Executive Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-10-02",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Lead Office Productivity Specialist",
    availableSeats: 4,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 11,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Microsoft Word Executive Document Design & Mail Merge",
      "Week 2: Microsoft Excel Data Entry, Formulas, Functions & Charting",
      "Week 3: Microsoft PowerPoint Dynamic Presentation Engineering",
      "Week 4: Outlook Email Management, Calendar Scheduling & OneDrive Cloud Sync",
      "Week 4: Comprehensive Office Simulation Project & Competency Examination"
    ],
    learningObjectives: [
      "Qualify for executive administrative, secretarial, and clerical IT roles",
      "Seamlessly integrate data across Word, Excel, and PowerPoint",
      "Manage professional email workflows and cloud file collaboration"
    ],
    entryRequirements: ["Open to school leavers, students, job seekers, and office staff."],
    scheduleDetails: "Monday to Thursday: 9:00 AM - 12:00 PM"
  },
  {
    id: "sc-ict-07",
    code: "AITI-ICT-007",
    title: "Internet & Digital Literacy",
    slug: "internet-digital-literacy",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Learn web navigation, efficient Google searching, online safety, evaluating information credibility, downloading files, and online public services.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "IT Infrastructure Specialist",
    availableSeats: 11,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 4,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Web browser fundamentals (Chrome, Edge), tabs, bookmarks, and history",
      "Advanced search operators (quotes, site:, filetype:) for accurate research",
      "Safe downloading, unpacking ZIP archives, and avoiding adware",
      "Online forms, uploading documents, and digital government/portal applications",
      "Recognizing online scams, fake news, and protecting personal data"
    ],
    learningObjectives: [
      "Search the internet efficiently for academic and professional resources",
      "Apply for admissions, jobs, and government services online accurately",
      "Identify fraudulent websites and protect digital identities"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-ict-08",
    code: "AITI-ICT-008",
    title: "Email & Online Productivity",
    slug: "email-online-productivity",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Professional email etiquette, Gmail/Outlook mastery, Google Calendar, Google Meet/Zoom, Google Drive, and cloud collaboration.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Online",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Senior Administrative Specialist",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Professional email writing: subject lines, formal greetings, sign-offs, and tone",
      "Inbox zero: labels, folders, filters, archiving, and spam management",
      "Scheduling meetings, calendar invites, time zones, and reminders",
      "Hosting and joining virtual video meetings on Google Meet and Zoom",
      "Google Docs & Drive: real-time multi-user document collaboration"
    ],
    learningObjectives: [
      "Write polished, grammatically sound business emails and responses",
      "Manage meeting schedules and appointments using digital calendars",
      "Collaborate with team members on shared cloud documents in real time"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-ict-09",
    code: "AITI-ICT-009",
    title: "Computer Typing & Office Productivity",
    slug: "computer-typing-office-productivity",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Accelerate typing speed and accuracy through ergonomic 10-finger touch typing drills, keyboard shortcuts, and rapid document transcription.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 20,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Typing & Ergonomics Suite)",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Typing & Office Skills Coach",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Sep 21, 2026"],
    courseOutline: [
      "Week 1: Home row keys (ASDF JKL;), posture, finger placement, and muscle memory",
      "Week 1: Top row (QWERTY) and bottom row (ZXCVB) drill sessions without looking at keyboard",
      "Week 2: Number row, punctuation keys, shift combinations, and speed pacing drills",
      "Week 2: Windows keyboard shortcuts (Ctrl+C, Ctrl+V, Alt+Tab) and 40+ WPM timed tests"
    ],
    learningObjectives: [
      "Achieve 35 - 55+ Words Per Minute (WPM) with 95%+ accuracy",
      "Eliminate 'hunt-and-peck' two-finger typing habits forever",
      "Transcribe written manuscripts and audio recordings rapidly into digital text"
    ],
    entryRequirements: ["Open to all students, secretaries, data entry clerks, and writers."],
    scheduleDetails: "Monday to Thursday: 1:00 PM - 3:30 PM"
  },
  {
    id: "sc-ict-10",
    code: "AITI-ICT-010",
    title: "File Management & Computer Operations",
    slug: "file-management-computer-operations",
    categoryId: "scc-1",
    categoryName: "ICT & Computer Fundamentals",
    category: "ICT & Computer Fundamentals",
    description: "Organize files efficiently: folder directory hierarchies, file extensions, archiving/unzipping, external backup drives, search indexing, and disk cleanup.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Systems Administrator",
    availableSeats: 10,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 5,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "File Explorer navigation, drives (C:, D:, USB), folder tree structures",
      "Creating, renaming, moving, copying, and deleting files and folders safely",
      "Understanding common file formats (.docx, .xlsx, .pdf, .jpg, .png, .mp4, .zip)",
      "Compression utilities (WinRAR/7-Zip), extracting archives, and password protection",
      "Disk cleanup, removing temporary files, Recycle Bin recovery, and USB backups"
    ],
    learningObjectives: [
      "Structure logical folder directories for home, office, and business records",
      "Find misplaced documents instantly using Windows advanced search filters",
      "Safeguard crucial business assets with scheduled external backup drives"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Friday: 9:00 AM - 12:00 PM"
  },

  // 2. DATA & ANALYTICS
  {
    id: "sc-dat-01",
    code: "AITI-DAT-001",
    title: "Excel for Data Analysis",
    slug: "excel-for-data-analysis",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "Transform raw spreadsheets into actionable business intelligence. Master XLOOKUP, PivotTables, conditional metrics, dynamic dashboards, and trend analysis.",
    duration: "3 Weeks",
    durationWeeks: 3,
    durationHours: 35,
    fee: 45000,
    feeGHS: 45000,
    trainingFee: 45000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Analytics Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Data Scientist & Analytics Lead",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Advanced formula syntax (XLOOKUP, INDEX/MATCH, SUMIFS, COUNTIFS, Nested IFs)",
      "Week 2: Data cleaning, text functions (TRIM, CONCAT, TEXTSPLIT), and Power Query basics",
      "Week 3: PivotTables, calculated fields, slicers, timelines, and dynamic visual dashboards"
    ],
    learningObjectives: [
      "Cleanse and restructure messy imported financial and sales datasets",
      "Perform exploratory multi-variable analysis with dynamic PivotTables",
      "Construct interactive executive KPI dashboards in Excel"
    ],
    entryRequirements: ["Basic Excel familiarity."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-dat-02",
    code: "AITI-DAT-002",
    title: "Advanced Microsoft Excel",
    slug: "advanced-microsoft-excel",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "Deep dive into financial modeling, dynamic array formulas (LET, LAMBDA, FILTER, UNIQUE), What-If scenario managers, solver, and macro automations.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Alpha & Virtual Lab",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mr. S. A. Adeleke",
    instructorName: "Mr. S. A. Adeleke",
    instructorTitle: "Financial Systems Consultant",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Advanced",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Dynamic array calculation engine (FILTER, SORT, UNIQUE, SEQUENCE, LET, LAMBDA)",
      "Week 1: Data validation, error handling (IFERROR, ISBLANK), and multi-sheet consolidation",
      "Week 2: What-If Analysis: Goal Seek, Data Tables, and Scenario Manager",
      "Week 2: Introduction to VBA Macro recording and workbook protection architecture"
    ],
    learningObjectives: [
      "Build complex financial forecast models without cell breakage",
      "Automate repetitive daily spreadsheet routines using recorded macros",
      "Audit intricate multi-department budget models with precision"
    ],
    entryRequirements: ["Intermediate Excel knowledge."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-dat-03",
    code: "AITI-DAT-003",
    title: "Data Analysis Fundamentals",
    slug: "data-analysis-fundamentals",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "The complete conceptual and practical introduction to the data analytics lifecycle: problem formulation, data collection, cleansing, exploratory stats, and storytelling.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Data Scientist",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: The Data Analytics Lifecycle: Ask, Prepare, Process, Analyze, Share, Act",
      "Week 1: Quantitative vs qualitative data, sample sizes, and descriptive statistics",
      "Week 2: Identifying outliers, skewness, missing values, and data integrity checks",
      "Week 2: Translating analytical findings into actionable business recommendations"
    ],
    learningObjectives: [
      "Frame business problems into testable analytical hypotheses",
      "Calculate central tendencies, variance, and correlations correctly",
      "Present executive data findings with clarity and visual appeal"
    ],
    entryRequirements: ["Basic computer and numeracy skills."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-dat-04",
    code: "AITI-DAT-004",
    title: "Data Cleaning & Preparation",
    slug: "data-cleaning-preparation",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "80% of data science is data prep. Learn Power Query ETL, text standardization, deduplication, unpivoting columns, handling nulls, and merging disparate datasets.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Data Scientist",
    availableSeats: 8,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 4,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Connecting to messy CSV, Excel, and Web data sources in Power Query",
      "Splitting columns by delimiters, stripping whitespace, and date formatting",
      "Unpivoting wide survey data into standardized tall relational datasets",
      "Merging (Left/Inner Joins) and Appending multiple monthly sales files",
      "Automating the recurring data refresh pipeline with a single click"
    ],
    learningObjectives: [
      "Automate hours of tedious manual data cleaning in minutes with Power Query",
      "Standardize disparate data feeds into clean, analysis-ready tables",
      "Eliminate duplicate records and formatting inconsistencies"
    ],
    entryRequirements: ["Basic spreadsheet experience."],
    scheduleDetails: "Monday to Friday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-dat-05",
    code: "AITI-DAT-005",
    title: "Data Visualization",
    slug: "data-visualization",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "Master the art and science of visual data storytelling. Choose the right chart types, color psychology, avoid chart junk, and build compelling infographics.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Visual Data Designer",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Visual perception, Gestalt principles, pre-attentive attributes, and color palette rules",
      "Week 1: Chart selection guide: Comparisons, compositions, distributions, and spatial relationships",
      "Week 2: Advanced visual charts: Treemaps, Waterfall charts, Heatmaps, and Sparklines",
      "Week 2: Designing executive presentation slides with data narratives and callouts"
    ],
    learningObjectives: [
      "Select the optimal chart format for any given business metric",
      "Design clear, impactful infographics that persuade decision-makers",
      "Eliminate visual noise to highlight critical business insights"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-dat-06",
    code: "AITI-DAT-006",
    title: "Power BI Fundamentals",
    slug: "power-bi-fundamentals",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "Learn Microsoft Power BI Desktop from scratch: Data modeling, DAX calculated measures, interactive visual canvases, and web report publishing.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 40000,
    feeGHS: 40000,
    trainingFee: 40000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Analytics Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Data Scientist",
    availableSeats: 5,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 7,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Sep 21, 2026"],
    courseOutline: [
      "Week 1: Connecting multiple data sources (Excel, SQL, Web) and Power Query transformations",
      "Week 1: Star Schema data modeling, table relationships, and cardinality (1:Many)",
      "Week 2: Essential DAX measures (CALCULATE, RELATED, SUMX, DIVIDE, DATESYTD)",
      "Week 2: Visual canvas design, drill-throughs, custom tooltips, and Power BI Service publishing"
    ],
    learningObjectives: [
      "Connect and transform multi-table enterprise data models",
      "Write accurate DAX business calculations for Year-over-Year tracking",
      "Build dynamic interactive dashboards ready for executive review"
    ],
    entryRequirements: ["Basic spreadsheet knowledge."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-dat-07",
    code: "AITI-DAT-007",
    title: "Power BI for Beginners",
    slug: "power-bi-for-beginners",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "A gentle, zero-jargon starter course in Power BI for people stepping into business intelligence and corporate reporting.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Data Scientist",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Installing Power BI Desktop and exploring the workspace interface",
      "Loading Excel spreadsheets and applying simple data type formatting",
      "Dragging and dropping cards, bar charts, donut charts, and maps onto the report canvas",
      "Applying slicers, page filters, and cross-filtering between visuals",
      "Exporting interactive reports to PDF and sharing screenshots with management"
    ],
    learningObjectives: [
      "Create your first professional Power BI dashboard in under 3 days",
      "Filter and slice company data interactively",
      "Understand how Power BI upgrades traditional static spreadsheet reports"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Friday: 9:00 AM - 12:00 PM"
  },
  {
    id: "sc-dat-08",
    code: "AITI-DAT-008",
    title: "Practical Data Analysis",
    slug: "practical-data-analysis",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "Hands-on, case-study-driven course analyzing real Nigerian retail, banking, and health sector datasets to solve operational bottlenecks.",
    duration: "3 Weeks",
    durationWeeks: 3,
    durationHours: 35,
    fee: 45000,
    feeGHS: 45000,
    trainingFee: 45000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Analytics Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Data Scientist",
    availableSeats: 6,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 6,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Case Study 1 - Retail Supermarket Sales & Inventory Turnover Optimization",
      "Week 2: Case Study 2 - Bank Customer Churn Analysis & Credit Risk Scoring",
      "Week 3: Case Study 3 - Public Health Clinic Patient Queue Management & Resource Planning",
      "Week 3: Final Portfolio Project Defense & Analytics Showcase"
    ],
    learningObjectives: [
      "Apply analytical frameworks to solve real-world industry problems",
      "Synthesize large data files into executive decision memos",
      "Build an industry-grade analytics portfolio to land analyst roles"
    ],
    entryRequirements: ["Excel or Power BI basics."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-dat-09",
    code: "AITI-DAT-009",
    title: "Introduction to SQL",
    slug: "introduction-to-sql",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "Learn Structured Query Language (SQL) for relational databases: SELECT queries, WHERE filters, GROUP BY aggregations, JOINs, and subqueries.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Zoom",
    venue: "Lab Alpha & Virtual Lab",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Database Administrator",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Relational database architecture, tables, primary/foreign keys, PostgreSQL setup",
      "Week 1: Writing foundational SELECT statements, DISTINCT, WHERE clauses, and ORDER BY",
      "Week 2: Aggregate functions (COUNT, SUM, AVG, MIN, MAX) and GROUP BY / HAVING clauses",
      "Week 2: Table Joins (INNER, LEFT, RIGHT, FULL OUTER) and Subqueries for reporting"
    ],
    learningObjectives: [
      "Extract filtered subsets of data from enterprise relational databases",
      "Join multiple database tables without creating duplicate records",
      "Write efficient queries to power BI tools and operational reports"
    ],
    entryRequirements: ["Basic computer and analytical interest."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-dat-10",
    code: "AITI-DAT-010",
    title: "Spreadsheet-Based Data Management",
    slug: "spreadsheet-based-data-management",
    categoryId: "scc-2",
    categoryName: "Data & Analytics",
    category: "Data & Analytics",
    description: "Manage large business datasets in Google Sheets and Excel: data entry validation rules, relational lookups, multi-user permissions, and audit logs.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Mr. S. A. Adeleke",
    instructorName: "Mr. S. A. Adeleke",
    instructorTitle: "Financial Systems Consultant",
    availableSeats: 9,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 6,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Database design rules in spreadsheets: 1 record per row, normalized columns",
      "Dropdown lists, range validations, and preventing erroneous user inputs",
      "Protecting sensitive formula cells, locking ranges, and role-based sharing",
      "Conditional formatting rules to highlight overdue invoices and low stock",
      "Automating recurring data backup and spreadsheet version histories"
    ],
    learningObjectives: [
      "Design fail-safe inventory and sales tracking spreadsheets for staff use",
      "Enforce data integrity with dropdown lists and validation rules",
      "Manage multi-user collaboration securely on Google Sheets and Excel"
    ],
    entryRequirements: ["Basic spreadsheet familiarity."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },

  // 3. ARTIFICIAL INTELLIGENCE
  {
    id: "sc-ai-01",
    code: "AITI-AI-001",
    title: "Introduction to Artificial Intelligence",
    slug: "introduction-to-artificial-intelligence",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Understand modern AI: Machine learning, neural networks, natural language processing, computer vision, and how AI is transforming every industry.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Online",
    venue: "Lab Alpha & Virtual Stream",
    startDate: "2026-09-07",
    endDate: "2026-09-11",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Lead AI Researcher & Systems Specialist",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Sep 21, 2026"],
    courseOutline: [
      "What is Artificial Intelligence? Narrow AI vs General AI vs Super AI",
      "How Machine Learning models learn from data patterns: Supervised vs Unsupervised",
      "Large Language Models (LLMs) explained in simple, visual terms",
      "AI in Healthcare, Agriculture, Finance, and Education in Africa",
      "The Future of Work: Skills needed to thrive in an AI-powered economy"
    ],
    learningObjectives: [
      "Demystify AI terminology and conceptual architectures",
      "Identify high-impact AI opportunities in your company or field",
      "Position yourself strategically for AI-driven workplace evolution"
    ],
    entryRequirements: ["Open to everyone interested in technology trends."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-ai-02",
    code: "AITI-AI-002",
    title: "AI for Beginners",
    slug: "ai-for-beginners",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "A friendly hands-on course getting started with practical consumer AI tools: ChatGPT, Google Gemini, Claude, and Copilot for everyday work.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior AI Specialist",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Setting up and navigating ChatGPT, Google Gemini, and Microsoft Copilot",
      "Writing clear conversational instructions to get high-quality answers",
      "Using AI to draft letters, summarize long documents, and brainstorm ideas",
      "Voice mode and mobile AI apps for on-the-go productivity",
      "AI limitations, fact-checking, and spotting generated hallucinations"
    ],
    learningObjectives: [
      "Use leading AI assistants confidently to save 5+ hours every week",
      "Draft professional memos, speeches, and outlines with AI assistance",
      "Verify AI outputs critically before using them in official work"
    ],
    entryRequirements: ["Basic computer or smartphone literacy."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-ai-03",
    code: "AITI-AI-003",
    title: "Generative AI",
    slug: "generative-ai",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Harness multimodal Generative AI: text generation, image synthesis (Midjourney, DALL-E), voice cloning (ElevenLabs), and code generation.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Tech Studio), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior AI Researcher",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Text-to-Text Generative Models: GPT-4o, Claude 3.5 Sonnet, context windows, and few-shot reasoning",
      "Week 1: Text-to-Image models: Midjourney, Stable Diffusion, parameter tuning (aspect ratios, stylize)",
      "Week 2: Text-to-Audio and voice cloning with ElevenLabs for voiceovers and podcasts",
      "Week 2: AI Code Generation with GitHub Copilot and Cursor for rapid app scaffolding"
    ],
    learningObjectives: [
      "Generate studio-grade marketing images and concept art from text prompts",
      "Synthesize hyper-realistic AI voiceovers for digital media and training videos",
      "Incorporate multimodal generative AI tools into creative and technical workflows"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-ai-04",
    code: "AITI-AI-004",
    title: "AI Tools for Productivity",
    slug: "ai-tools-for-productivity",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Multiply individual and team output with specialized AI productivity tools: Notion AI, Gamma presentations, Otter meeting transcription, and Zapier AI automation.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Digital Productivity Specialist",
    availableSeats: 9,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 11,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Gamma App: Generating 10-slide presentation decks with AI in 60 seconds",
      "Otter.ai & Fireflies: Automated meeting recordings, transcripts, and action items",
      "Notion AI: Knowledge base organization, research synthesis, and task tracking",
      "Perplexity AI: Deep-dive academic research with verified inline web citations",
      "Zapier / Make.com AI: Connecting email, spreadsheets, and messaging automatically"
    ],
    learningObjectives: [
      "Automate meeting summaries and task delegation without manual note-taking",
      "Build stunning visual slide decks in a fraction of traditional design time",
      "Streamline daily research with real-time AI citation engines"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-ai-05",
    code: "AITI-AI-005",
    title: "AI for Business",
    slug: "ai-for-business",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Executive and managerial training: AI customer support chatbots, automated sales copywriting, market intelligence, sentiment analysis, and ROI calculation.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Executive Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior AI Strategist",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: AI business strategy, identifying operational bottlenecks, and vendor evaluation",
      "Week 1: Deploying no-code customer service AI chatbots trained on your company FAQs",
      "Week 2: AI-driven competitive market research and customer feedback sentiment analysis",
      "Week 2: Enterprise data privacy, intellectual property risk management, and AI compliance"
    ],
    learningObjectives: [
      "Implement AI customer service bots that handle 70% of routine client inquiries",
      "Formulate an organizational AI adoption roadmap with measurable ROI",
      "Protect proprietary business data when deploying commercial AI tools"
    ],
    entryRequirements: ["Business owners, managers, executives, and department leads."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-ai-06",
    code: "AITI-AI-006",
    title: "AI for Education",
    slug: "ai-for-education",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Designed for teachers, lecturers, tutors, and school administrators: AI lesson planning, automated quiz generation, personalized learning, and plagiarism policies.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "EdTech & Learning Specialist",
    availableSeats: 12,
    totalSeats: 25,
    maxSeats: 25,
    maxParticipants: 25,
    enrolledCount: 13,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Generating comprehensive 12-week lesson plans aligned with curriculum standards in minutes",
      "Creating differentiated exam questions, multiple choice quizzes, and grading rubrics with AI",
      "Interactive AI tutors: prompting AI to explain difficult concepts across multiple grade levels",
      "Educational AI ethics: addressing student plagiarism, detection tools, and ethical guidelines",
      "Building engaging educational slide decks, diagrams, and worksheets with AI"
    ],
    learningObjectives: [
      "Save 10+ hours per week on lesson note preparation and assessment creation",
      "Personalize study materials to match varying student learning speeds",
      "Establish clear institutional policies regarding responsible student AI usage"
    ],
    entryRequirements: ["Educators, tutors, school administrators, and students."],
    scheduleDetails: "Monday to Friday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-ai-07",
    code: "AITI-AI-007",
    title: "Prompt Engineering",
    slug: "prompt-engineering",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Master the art and science of directing AI models with precision: zero-shot, few-shot, Chain-of-Thought, role prompting, format constraints, and prompt debugging.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Tech Studio), AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior AI Researcher",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Sep 28, 2026"],
    courseOutline: [
      "Anatomy of an Effective Prompt: Role, Context, Task, Constraints, and Output Format",
      "Advanced Techniques: Few-Shot In-Context Learning and Chain-of-Thought (CoT) Prompting",
      "Extracting deterministic JSON, Markdown tables, and structured data from AI models",
      "Debugging prompt failures, eliminating hallucinations, and setting safety guardrails",
      "Building a custom organizational Prompt Template Library for repeatable results"
    ],
    learningObjectives: [
      "Extract consistent, enterprise-grade structured data from LLMs",
      "Eliminate vague and generic AI responses through advanced constraint engineering",
      "Build reusable prompt templates for entire corporate teams"
    ],
    entryRequirements: ["Basic familiarity with ChatGPT or other AI chatbots."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-ai-08",
    code: "AITI-AI-008",
    title: "ChatGPT & AI Productivity Tools",
    slug: "chatgpt-ai-productivity-tools",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Deep practical training in ChatGPT Plus (GPT-4o), Custom GPTs, Advanced Data Analysis (Python execution), Web Browsing, and canvas document editing.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior AI Specialist",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Advanced ChatGPT features: GPT-4o vision capabilities, voice interface, canvas editor",
      "Week 1: Advanced Data Analysis: uploading CSVs, generating charts, and running statistical Python code",
      "Week 2: Building Custom GPTs: instructions, knowledge file uploads, and custom actions",
      "Week 2: Integrating ChatGPT with Google Workspace, Slack, and web automation tools"
    ],
    learningObjectives: [
      "Build custom bespoke AI assistants configured for specific business roles",
      "Perform instant dataset analysis and chart plotting via natural language",
      "Automate complex drafting and editing workflows using ChatGPT Canvas"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-ai-09",
    code: "AITI-AI-009",
    title: "AI Content Creation",
    slug: "ai-content-creation",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Produce viral blog posts, social media captions, video scripts, YouTube thumbnails, podcast voiceovers, and marketing ad copy using AI tools.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Online",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Digital Media Strategist",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: AI copywriting: viral hooks, storytelling frameworks (AIDA, PAS), and tone calibration",
      "Week 1: Generating high-CTR YouTube and TikTok video scripts and carousel outlines",
      "Week 2: AI image synthesis for social media graphics, blog banners, and product mockups",
      "Week 2: ElevenLabs & CapCut AI: automated voiceovers, subtitle generation, and video assembly"
    ],
    learningObjectives: [
      "Create 30 days of high-engagement social media content in a single afternoon",
      "Produce voiceover-narrated short-form videos without recording your own voice",
      "Maintain a consistent, recognizable brand voice across AI-generated copy"
    ],
    entryRequirements: ["Basic computer or smartphone usage."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-ai-10",
    code: "AITI-AI-010",
    title: "Responsible & Ethical AI",
    slug: "responsible-ethical-ai",
    categoryId: "scc-3",
    categoryName: "Artificial Intelligence",
    category: "Artificial Intelligence",
    description: "Understand AI governance, bias mitigation, data privacy laws (NDPR/GDPR), copyright considerations, deepfake detection, and ethical deployment standards.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior AI Researcher",
    availableSeats: 14,
    totalSeats: 25,
    maxSeats: 25,
    maxParticipants: 25,
    enrolledCount: 11,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Algorithmic bias, representation disparity, and fair AI decision-making",
      "Data privacy regulations: NDPR, GDPR, and confidential data leakage risks",
      "Intellectual property, copyright ownership of AI outputs, and commercial licensing",
      "Synthetic media, deepfakes, misinformation, and verification tools",
      "Drafting an institutional Responsible AI Policy for your organization"
    ],
    learningObjectives: [
      "Audit AI tools for privacy risks before feeding internal company records",
      "Navigate copyright and commercial ownership of AI-created assets",
      "Formulate transparent, ethical AI guidelines for institutional governance"
    ],
    entryRequirements: ["Open to professionals, managers, lawyers, and tech enthusiasts."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },

  // 4. GRAPHICS & CREATIVE DESIGN
  {
    id: "sc-des-01",
    code: "AITI-DES-001",
    title: "Graphics Design Fundamentals",
    slug: "graphics-design-fundamentals",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Core principles of visual design: color theory, typography pairings, grid alignment, negative space, visual hierarchy, and composition rules.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Graphics Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Creative Director & Visual Designer",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: The 7 Elements of Design: Line, Shape, Form, Color, Texture, Space, and Value",
      "Week 1: Color Theory: RGB vs CMYK, complementary palettes, and emotional color psychology",
      "Week 2: Typography fundamentals: Serif, Sans-Serif, Display fonts, leading, kerning, tracking",
      "Week 2: Layout architecture: Grid systems, rule of thirds, focal points, and balance"
    ],
    learningObjectives: [
      "Critique and improve visual designs using objective mathematical and spatial principles",
      "Pair fonts and colors harmoniously for print and digital media",
      "Eliminate cluttered, amateurish layout habits"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-des-02",
    code: "AITI-DES-002",
    title: "Professional Graphics Design",
    slug: "professional-graphics-design",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "An intensive 4-week professional design boot camp mastering Adobe Photoshop, Illustrator, and CorelDRAW for client brand design and print pre-press.",
    duration: "4 Weeks",
    durationWeeks: 4,
    durationHours: 50,
    fee: 45000,
    feeGHS: 45000,
    trainingFee: 45000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Graphics Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-10-02",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Creative Director",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Design theory, typography hierarchy, and Photoshop workspace mastery",
      "Week 2: Photoshop photo manipulation, masking, lighting, shadows, and mockups",
      "Week 3: Illustrator vector logo design, icon sets, geometric construction, and badges",
      "Week 4: CorelDRAW pre-press, billboard layouts, business cards, flyers, and portfolio exhibition"
    ],
    learningObjectives: [
      "Build comprehensive corporate visual identities (Logos, Stationery, Brand Guidelines)",
      "Retouch high-resolution photography with realistic lighting and shadows",
      "Prepare print-ready CMYK separation files for industrial printing presses"
    ],
    entryRequirements: ["Basic computer navigation."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-des-03",
    code: "AITI-DES-003",
    title: "Adobe Photoshop",
    slug: "adobe-photoshop",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Master world-standard photo editing and digital compositing: layers, pen tool selections, retouching, smart objects, filters, and 3D mockups.",
    duration: "3 Weeks",
    durationWeeks: 3,
    durationHours: 35,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Graphics Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Creative Director",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Photoshop interface, layers, layer masks, selection tools, and the precision Pen Tool",
      "Week 2: Retouching portraits (Frequency Separation, Dodge & Burn, blemish removal, skin tone grading)",
      "Week 3: Advanced compositing, lighting/shadow matching, smart objects, and 3D product mockup packaging"
    ],
    learningObjectives: [
      "Execute high-end commercial beauty and product photo retouching",
      "Create convincing visual photo manipulations from multiple asset sources",
      "Package digital designs into realistic 3D photorealistic mockups"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-des-04",
    code: "AITI-DES-004",
    title: "Adobe Illustrator",
    slug: "adobe-illustrator",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Master precision vector graphic creation: pen tool, curvature tool, shape builder, pathfinder, typography styling, gradients, and scalable vector exports (SVG/EPS/PDF).",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Senior Brand Identity Designer",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Vector vs raster concepts, artboard management, Pen Tool mastery, and Shape Builder",
      "Week 1: Color swatches, gradient meshes, stroke weights, arrowheads, and brush libraries",
      "Week 2: Logo geometry grids, golden ratio principles, and monograms",
      "Week 2: Preparing vector icons, badges, apparel graphics, and packaging cut lines"
    ],
    learningObjectives: [
      "Craft clean vector logos that scale infinitely without pixelation",
      "Design custom icon systems and branded geometric vectors",
      "Export standardized SVG, EPS, and high-res vector PDF files"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-des-05",
    code: "AITI-DES-005",
    title: "CorelDRAW",
    slug: "coreldraw",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Learn Nigeria's most popular commercial printing graphic application: vector drawing, powerclip, pre-press separation, signage, and large format billboard design.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Print & Production Specialist",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: CorelDRAW workspace, pick tool, shape tool, bezier curves, and artistic media brushes",
      "Week 1: PowerClip frame containers, contour effects, drop shadows, and extrusions",
      "Week 2: Designing corporate letterheads, business cards, wedding invitation cards, and flyers",
      "Week 2: Large format banner layouts, bleed margins, crop marks, and direct-to-plate pre-press"
    ],
    learningObjectives: [
      "Operate CorelDRAW with high production speed for commercial printing hubs",
      "Design wedding programs, funeral brochures, and corporate stationery to scale",
      "Prepare color separations and print files for commercial offset and flex machines"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-des-06",
    code: "AITI-DES-006",
    title: "Canva Design",
    slug: "canva-design",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Fast-track visual creation for entrepreneurs and marketers: Brand Kit setup, social media flyers, carousels, pitch decks, and Canva Magic Studio AI tools.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Digital Media Specialist",
    availableSeats: 10,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 5,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Sep 28, 2026"],
    courseOutline: [
      "Canva interface, Brand Kit setup (custom fonts, hex color palettes, and logos)",
      "Social media graphics: Instagram single posts, high-converting carousels, and stories",
      "Business collateral: Price lists, invoices, receipts, flyers, and letterheads",
      "Canva Magic Studio AI: Magic Switch, background removal, eraser, and text expansion",
      "Exporting high-resolution formats (PDF Print, SVG, MP4) and content scheduling"
    ],
    learningObjectives: [
      "Design consistent corporate social media graphics in under 15 minutes",
      "Generate interactive presentation decks and downloadable PDF brochures",
      "Maintain strict visual brand consistency across multiple marketing formats"
    ],
    entryRequirements: ["No prior design experience required."],
    scheduleDetails: "Monday to Friday: 1:30 PM - 4:30 PM"
  },
  {
    id: "sc-des-07",
    code: "AITI-DES-007",
    title: "Social Media Graphics",
    slug: "social-media-graphics",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Create scroll-stopping visuals tailored for Instagram, TikTok, LinkedIn, Facebook, and X: aspect ratios, carousel storytelling, and promotional ads.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Creative Director",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Platform dimension guidelines: Square (1:1), Portrait (4:5), Story/Reel (9:16), Landscape (16:9)",
      "Designing multi-slide seamless Instagram carousels that drive high saves and shares",
      "Sponsored Ad Creatives: visual hooks, call-to-action buttons, and mobile contrast rules",
      "Creating branded YouTube thumbnails with high click-through rates (CTR)",
      "Automating batch graphic generation using templates and dynamic text"
    ],
    learningObjectives: [
      "Design high-converting ad graphics that capture mobile viewers in under 2 seconds",
      "Build seamless carousel graphics that boost algorithm engagement",
      "Format visual assets correctly for every major social media channel"
    ],
    entryRequirements: ["Basic design interest."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-des-08",
    code: "AITI-DES-008",
    title: "Flyer & Poster Design",
    slug: "flyer-poster-design",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Specialized training in event, church, business, and political flyer design: lighting effects, cutouts, typography layouts, 3D text, and print standards.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Creative Director",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Focal point mastery, cutting out speaker portraits, color grading subject images",
      "Week 1: Creative background blending: textures, particles, flares, and ambient glow effects",
      "Week 2: 3D typography styling, metallic and glossy text effects, and sub-headline balance",
      "Week 2: Layout composition for A5/A4 physical flyers vs A4 e-posters for WhatsApp status"
    ],
    learningObjectives: [
      "Design eye-catching event, conference, and church flyers from client briefs",
      "Apply cinematic lighting, glowing neon effects, and particle blends seamlessly",
      "Manage sponsor logos, speaker details, and venue badges professionally"
    ],
    entryRequirements: ["Photoshop or CorelDRAW familiarity."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-des-09",
    code: "AITI-DES-009",
    title: "Branding Design",
    slug: "branding-design",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Strategic corporate visual identity development: brand positioning, color psychology, logo usage rules, corporate stationery, and brand guidelines manuals.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Brand Identity Lead",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Brand strategy, mission discovery, mood boards, and target audience personas",
      "Week 1: Primary logo, secondary mark, submarks, favicons, and clear space rules",
      "Week 2: Corporate stationery: Letterheads, business cards, staff ID cards, and envelopes",
      "Week 2: Compiling a 16-page professional Brand Style Guide PDF for corporate clients"
    ],
    learningObjectives: [
      "Charge premium retainer fees for full corporate brand identity systems",
      "Author standardized brand guideline manuals for enterprise companies",
      "Deliver organized asset packages (PNG, SVG, PDF, AI) to clients"
    ],
    entryRequirements: ["Illustrator, CorelDRAW, or Photoshop skills."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-des-10",
    code: "AITI-DES-010",
    title: "Logo Design",
    slug: "logo-design",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Master conceptual logo design: wordmarks, lettermarks, pictorial marks, abstract symbols, mascots, emblems, vector grid systems, and presentation decks.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Brand Identity Lead",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: The 7 types of logos and the anatomy of world-class brand symbols",
      "Week 1: Mind mapping, sketching 30+ concepts on paper, and selecting winning ideas",
      "Week 2: Vectorizing sketches in Illustrator using geometric grids and golden ratio circles",
      "Week 2: Client presentation psychology: Building 3D mockups and pitch deck presentations"
    ],
    learningObjectives: [
      "Translate abstract company values into simple, memorable vector logo symbols",
      "Use mathematical grid systems to refine curves and symmetry with precision",
      "Present concept logos to clients in ways that secure instant approvals"
    ],
    entryRequirements: ["Basic drawing or vector graphic interest."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-des-11",
    code: "AITI-DES-011",
    title: "Digital Illustration",
    slug: "digital-illustration",
    categoryId: "scc-4",
    categoryName: "Graphics & Creative Design",
    category: "Graphics & Creative Design",
    description: "Draw expressive digital characters, editorial art, storybook illustrations, isometric graphics, and vector scenes using graphics tablets and Illustrator.",
    duration: "3 Weeks",
    durationWeeks: 3,
    durationHours: 35,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (Illustration Studio), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-25",
    instructor: "Mr. T. E. Alabi",
    instructorName: "Mr. T. E. Alabi",
    instructorTitle: "Illustrator & Visual Artist",
    availableSeats: 6,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 6,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Digital drawing tablets, pressure sensitivity, brush calibration, and line weight dynamics",
      "Week 2: Character anatomy, facial expressions, pose dynamics, and flat color blocking",
      "Week 3: Cel-shading, soft ambient occlusion, gradient lighting, background scenery, and exports"
    ],
    learningObjectives: [
      "Illustrate custom character graphics for children's books, games, and web apps",
      "Produce isometric vector scenes for modern tech landing pages",
      "Master digital painting workflows on graphics drawing tablets"
    ],
    entryRequirements: ["Passion for drawing and visual creativity."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  }
];
