import { ShortCourse } from '../../src/types';

export const coursesPart3: ShortCourse[] = [
  // ----------------------------------------------------
  // CATEGORY 9: CYBERSECURITY & SAFE COMPUTING
  // ----------------------------------------------------
  {
    id: "sc-sec-01",
    code: "AITI-SEC-001",
    title: "Cybersecurity Fundamentals",
    slug: "cybersecurity-fundamentals",
    categoryId: "scc-9",
    categoryName: "Cybersecurity & Safe Computing",
    category: "Cybersecurity & Safe Computing",
    description: "Foundational information security: CIA triad (Confidentiality, Integrity, Availability), malware types, threat vectors, firewalls, and security defense.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Cyber Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Lead Cybersecurity Specialist",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Core security principles: Confidentiality, Integrity, Availability (CIA) and Authentication",
      "Week 1: Attack vectors: Ransomware, Spyware, Trojan horses, Keyloggers, and Zero-day vulnerabilities",
      "Week 2: Network defense: Windows Defender Firewall rules, Port scanning with Nmap, and VPN tunneling",
      "Week 2: Vulnerability management, patch cadence, and basic incident response procedures"
    ],
    learningObjectives: [
      "Understand how cyber criminals breach networks and steal sensitive data",
      "Configure host firewalls and endpoint protection to block malicious intrusions",
      "Perform vulnerability scans to identify open ports and unpatched systems"
    ],
    entryRequirements: ["Basic computer literacy."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-sec-02",
    code: "AITI-SEC-002",
    title: "Cyber Awareness & Online Safety",
    slug: "cyber-awareness-online-safety",
    categoryId: "scc-9",
    categoryName: "Cybersecurity & Safe Computing",
    category: "Cybersecurity & Safe Computing",
    description: "Defend against social engineering, deceptive phishing emails, fraudulent bank SMS alerts, WhatsApp account takeovers, and ATM card skimming.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Cybersecurity Awareness Officer",
    availableSeats: 12,
    totalSeats: 25,
    maxSeats: 25,
    maxParticipants: 25,
    enrolledCount: 13,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Social engineering psychology: How hackers manipulate urgency, authority, and fear",
      "Spotting phishing emails, fake sender headers, malicious attachments, and lookalike domains",
      "Securing WhatsApp and social media with 2FA PIN codes to prevent SIM swap hijackings",
      "Online banking security: Safe BVN handling, OTP protections, and fake bank transfer alerts",
      "Public Wi-Fi hazards: Why you should never check bank apps on open cafe networks"
    ],
    learningObjectives: [
      "Recognize deceptive phishing emails and malicious links in under 5 seconds",
      "Protect personal and corporate bank accounts from digital fraud",
      "Secure WhatsApp and social accounts against unauthorized takeover attempts"
    ],
    entryRequirements: ["Open to everyone."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-sec-03",
    code: "AITI-SEC-003",
    title: "Digital Privacy & Security",
    slug: "digital-privacy-security",
    categoryId: "scc-9",
    categoryName: "Cybersecurity & Safe Computing",
    category: "Cybersecurity & Safe Computing",
    description: "Protect your digital footprint: password managers (Bitwarden), Two-Factor Authentication (2FA/TOTP), encrypted messaging (Signal), and browser ad-trackers.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Beta & Virtual Classroom",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Cybersecurity Specialist",
    availableSeats: 10,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 10,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "The end of weak passwords: Setting up and migrating to Bitwarden password manager",
      "Two-Factor Authentication: Replacing insecure SMS 2FA with Authenticator apps (Google/YubiKey)",
      "Eliminating web trackers: Privacy browsers (Brave), uBlock Origin, and DNS over HTTPS",
      "Encrypted communications: End-to-end encryption protocols in Signal vs Telegram vs WhatsApp",
      "Erasing your digital trail: Managing Google activity logs and location tracking permissions"
    ],
    learningObjectives: [
      "Eliminate password reuse and generate unhackable 20+ character master keys",
      "Deploy hardware and app-based 2-factor authentication across all accounts",
      "Prevent big-tech surveillance tracking and targeted data harvesting"
    ],
    entryRequirements: ["Basic smartphone or computer usage."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },
  {
    id: "sc-sec-04",
    code: "AITI-SEC-004",
    title: "Safe Computing",
    slug: "safe-computing",
    categoryId: "scc-9",
    categoryName: "Cybersecurity & Safe Computing",
    category: "Cybersecurity & Safe Computing",
    description: "Best practices for workstations: USB drive disinfection, verifying software cryptographic checksums (SHA256), BitLocker full-disk encryption, and secure deletion.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Systems Security Engineer",
    availableSeats: 8,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 7,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "Beginner",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Preventing USB autorun malware infections when transferring files across office PCs",
      "Verifying genuine software downloads using SHA-256 hash checksum tools",
      "Enabling BitLocker full disk encryption to protect laptops if stolen",
      "Standard user accounts vs Administrator privilege separation on Windows",
      "Secure file shredding to permanently erase confidential company documents"
    ],
    learningObjectives: [
      "Safeguard company laptops against physical theft and data extraction",
      "Prevent rogue USB drives from compromising entire local networks",
      "Implement the principle of least privilege across everyday office computers"
    ],
    entryRequirements: ["Basic computer usage."],
    scheduleDetails: "Monday to Friday: 1:30 PM - 4:30 PM"
  },
  {
    id: "sc-sec-05",
    code: "AITI-SEC-005",
    title: "Mobile Security",
    slug: "mobile-security",
    categoryId: "scc-9",
    categoryName: "Cybersecurity & Safe Computing",
    category: "Cybersecurity & Safe Computing",
    description: "Harden Android and iOS smartphones: app permission audits, rogue APK detection, remote wipe configuration, biometric locks, and anti-theft tracking.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 20000,
    feeGHS: 20000,
    trainingFee: 20000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-21",
    endDate: "2026-09-25",
    instructor: "Engr. A. F. Taiwo",
    instructorName: "Engr. A. F. Taiwo",
    instructorTitle: "Mobile Security Analyst",
    availableSeats: 9,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 6,
    certificate: "Certificate of Attendance",
    certificateType: "Certificate of Attendance",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 21, 2026", "Oct 19, 2026"],
    courseOutline: [
      "Auditing dangerous app permissions (Microphone, Camera, SMS, Accessibility services)",
      "The dangers of sideloading cracked APK files and how they install hidden spyware",
      "Configuring Google Find My Device / Apple Find My with remote lock and remote erase",
      "SIM card lock PINs to prevent thieves from moving your SIM to another phone",
      "Secure mobile banking habits and encrypted backup storage"
    ],
    learningObjectives: [
      "Lock down smartphones against theft, SIM cloning, and unauthorized bank transfers",
      "Detect and uninstall malicious spyware apps hiding in the background",
      "Remotely locate and wipe lost or stolen smartphones instantly"
    ],
    entryRequirements: ["Android or iOS smartphone."],
    scheduleDetails: "Monday to Friday: 10:00 AM - 1:00 PM"
  },

  // ----------------------------------------------------
  // CATEGORY 10: EXECUTIVE, CORPORATE & WORKPLACE TECH
  // ----------------------------------------------------
  {
    id: "sc-corp-01",
    code: "AITI-CORP-001",
    title: "Executive Tech Training",
    slug: "executive-tech-training",
    categoryId: "scc-10",
    categoryName: "Executive, Corporate & Workplace Tech",
    category: "Executive, Corporate & Workplace Tech",
    description: "High-level technology mastery for CEOs, Directors, and Executives: digital signature workflows, cloud document approvals, secure zoom board meetings, and AI strategic briefings.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 50000,
    feeGHS: 50000,
    trainingFee: 50000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Executive Lounge Lab",
    trainingMode: "Executive Lounge Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Executive Technology Boardroom, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-11",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Executive Technology Consultant",
    availableSeats: 4,
    totalSeats: 8,
    maxSeats: 8,
    maxParticipants: 8,
    enrolledCount: 4,
    certificate: "Executive Certificate of Tech Competency",
    certificateType: "Executive Certificate of Tech Competency",
    status: "published",
    level: "Executive",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Paperless executive workflows: Reviewing, annotating, and digitally signing PDF contracts on iPad/tablets",
      "Encrypted board communications, password-protected board packs, and secure cloud storage",
      "Leading effective hybrid board meetings with Zoom/Teams and interactive digital whiteboards",
      "Executive AI briefing: How LLMs impact industry strategy, labor costs, and market positioning",
      "VIP cybersecurity protection: Protecting personal accounts from spear-phishing and executive impersonation"
    ],
    learningObjectives: [
      "Operate a 100% paperless executive office with digital signature authority",
      "Lead high-stakes hybrid board meetings with seamless tech fluidity",
      "Leverage AI tools for strategic decision-making and executive briefings"
    ],
    entryRequirements: ["Business Executives, Directors, Permanent Secretaries, and CEOs."],
    scheduleDetails: "Monday to Friday: 9:00 AM - 12:00 PM (Executive Lounge)"
  },
  {
    id: "sc-corp-02",
    code: "AITI-CORP-002",
    title: "Corporate ICT Brush-Up",
    slug: "corporate-ict-brush-up",
    categoryId: "scc-10",
    categoryName: "Executive, Corporate & Workplace Tech",
    category: "Executive, Corporate & Workplace Tech",
    description: "Rapid modernization for organizational workforces: professional email etiquette, advanced Word report styling, intermediate Excel data tables, and cloud file sharing.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 15,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Corporate Suite), AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Corporate Training Lead",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Corporate Training Completion",
    certificateType: "Certificate of Corporate Training Completion",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Day 1: Corporate email standards, Outlook scheduling, calendar coordination, and out-of-office rules",
      "Day 2: Word report formatting: official corporate styles, table styling, and automated tables of contents",
      "Day 3: Excel productivity: VLOOKUP/XLOOKUP, SUMIFS, PivotTables, and error-free invoice generation",
      "Day 4: PowerPoint slide modernization: eliminating text-heavy slides with clean visual layouts",
      "Day 5: Enterprise cloud collaboration on Microsoft Teams and Google Workspace"
    ],
    learningObjectives: [
      "Standardize document and report formatting across the entire organization",
      "Eliminate spreadsheet calculation errors in departmental reporting",
      "Accelerate daily administrative tasks by 40% through modern office software shortcuts"
    ],
    entryRequirements: ["Corporate employees and administrative staff."],
    scheduleDetails: "Monday to Friday: 9:00 AM - 12:00 PM"
  },
  {
    id: "sc-corp-03",
    code: "AITI-CORP-003",
    title: "Administrative Tech Training",
    slug: "administrative-tech-training",
    categoryId: "scc-10",
    categoryName: "Executive, Corporate & Workplace Tech",
    category: "Executive, Corporate & Workplace Tech",
    description: "Specialized for Executive Assistants, Office Managers, and Secretaries: appointment booking tools, travel itineraries, petty cash spreadsheets, and minute taking.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Senior Administrative Specialist",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Digital minute-taking: audio transcription tools (Otter/Whisper) and executive summary formatting",
      "Week 1: Automated appointment scheduling with Calendly and executive Google/Outlook calendar management",
      "Week 2: Designing automated Petty Cash, Requisition, and Office Supplies tracking spreadsheets in Excel",
      "Week 2: Travel logistics management: booking portals, digital itinerary design, and expense receipt filing"
    ],
    learningObjectives: [
      "Deliver pristine, executive-ready meeting minutes within 2 hours of meeting completion",
      "Automate meeting scheduling and prevent double-booking conflicts completely",
      "Track office petty cash and procurement expenditures with zero financial discrepancies"
    ],
    entryRequirements: ["Secretaries, administrative assistants, and office managers."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-corp-04",
    code: "AITI-CORP-004",
    title: "Computer Training for Teachers",
    slug: "computer-training-for-teachers",
    categoryId: "scc-10",
    categoryName: "Executive, Corporate & Workplace Tech",
    category: "Executive, Corporate & Workplace Tech",
    description: "Equip primary and secondary educators: typing exam questions, calculating terminal termly grades in Excel, interactive smartboards, and Google Classroom.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta (EdTech Lab), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "EdTech Faculty Lead",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Typing and formatting school exam papers, multiple choice layouts, and mathematical formulas in Word",
      "Week 1: Google Classroom & Edmodo: Creating online classrooms, assigning homework, and collecting submissions",
      "Week 2: Excel Grade Sheets: Automating continuous assessment (CA), exam scores, total percentages, positions, and remarks",
      "Week 2: Interactive classroom slide presentations: embedding educational animations and YouTube clips into PowerPoint"
    ],
    learningObjectives: [
      "Eliminate manual grading math errors with automated Excel student score sheets",
      "Format neat, professional school exam papers and termly lesson notes",
      "Teach engaging digital lessons using modern classroom projection tools"
    ],
    entryRequirements: ["Teachers, tutors, and educational instructors."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-corp-05",
    code: "AITI-CORP-005",
    title: "IT for School Administrators",
    slug: "it-for-school-administrators",
    categoryId: "scc-10",
    categoryName: "Executive, Corporate & Workplace Tech",
    category: "Executive, Corporate & Workplace Tech",
    description: "Manage school operations digitally: School Management Systems (SMS), student report card generation, automated school fee tracking, and bulk SMS/WhatsApp notices.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Beta, AITI Tanke Campus",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Engr. M. I. Ibrahim",
    instructorName: "Engr. M. I. Ibrahim",
    instructorTitle: "School Management Systems Specialist",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: School Information Systems (SIS) architecture: Student enrolment, class rosters, and teacher allocations",
      "Week 1: Automating end-of-term printable report cards with student photos, grades, and head teacher signatures",
      "Week 2: Financial management: School fee payment reconciliations, outstanding fee defaulter lists, and automated receipts",
      "Week 2: Parent communication channels: Bulk SMS portals, WhatsApp broadcast channels, and event notices"
    ],
    learningObjectives: [
      "Deploy a modern digital School Management Portal for admissions, results, and fees",
      "Generate hundreds of student report cards with a single click at term end",
      "Collect and track school fees with transparent digital audit trails"
    ],
    entryRequirements: ["School owners, principals, registrars, and bursars."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 1:00 PM"
  },
  {
    id: "sc-corp-06",
    code: "AITI-CORP-006",
    title: "Tech for Business Owners",
    slug: "tech-for-business-owners",
    categoryId: "scc-10",
    categoryName: "Executive, Corporate & Workplace Tech",
    category: "Executive, Corporate & Workplace Tech",
    description: "Practical digital operations for SME founders: POS systems, computerized bookkeeping, digital stock inventory, Google Maps location setup, and staff monitoring.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 30000,
    feeGHS: 30000,
    trainingFee: 30000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mr. S. A. Adeleke",
    instructorName: "Mr. S. A. Adeleke",
    instructorTitle: "SME Tech Consultant",
    availableSeats: 7,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 8,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Point of Sale (POS) and inventory software setup: barcode scanning, receipts, and low-stock alerts",
      "Week 1: Google Business Profile optimization: Putting your shop/office on Google Maps to attract nearby customers",
      "Week 2: Simple digital bookkeeping (QuickBooks/Excel): Daily cash flow, profit & loss, and debt recovery tracking",
      "Week 2: Remote staff monitoring and digital attendance clocking systems"
    ],
    learningObjectives: [
      "Prevent retail inventory theft and cash leakage using computerized POS systems",
      "Attract daily walk-in foot traffic by ranking high on Google Maps search",
      "Monitor company sales and profit margins in real time from your mobile phone"
    ],
    entryRequirements: ["Business owners and entrepreneurs."],
    scheduleDetails: "Monday to Thursday: 2:00 PM - 5:00 PM"
  },
  {
    id: "sc-corp-07",
    code: "AITI-CORP-007",
    title: "Digital Tools for NGO & Project Staff",
    slug: "digital-tools-for-ngo-project-staff",
    categoryId: "scc-10",
    categoryName: "Executive, Corporate & Workplace Tech",
    category: "Executive, Corporate & Workplace Tech",
    description: "Tailored for development workers: mobile field data collection (KoboToolbox/ODK), Gantt chart project tracking (Asana/Trello), donor report writing, and infographics.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 25,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Hybrid",
    trainingMode: "Hybrid",
    location: "AITI Tanke Main Campus & Live Zoom",
    venue: "Lab Alpha & Virtual Classroom",
    startDate: "2026-09-14",
    endDate: "2026-09-25",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "M&E and Data Systems Specialist",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "Intermediate",
    featured: false,
    active: true,
    upcomingBatches: ["Sep 14, 2026", "Oct 12, 2026"],
    courseOutline: [
      "Week 1: Field data collection: Designing mobile survey questionnaires in KoboToolbox / ODK Collect with GPS tagging",
      "Week 1: Offline data synchronization from rural field sites to cloud servers and automated cleaning",
      "Week 2: Project management tools: Asana, Trello Kanban boards, Gantt chart milestones, and task dependencies",
      "Week 2: Donor report design: Combining analytical survey charts, beneficiary stories, and infographics into publication-ready PDFs"
    ],
    learningObjectives: [
      "Deploy robust offline mobile survey questionnaires for field enumerators",
      "Manage multi-stakeholder international development projects with Gantt chart precision",
      "Author compelling visual donor reports that satisfy international funding agencies"
    ],
    entryRequirements: ["NGO personnel, project managers, and M&E officers."],
    scheduleDetails: "Monday to Friday: 5:00 PM - 7:00 PM"
  },

  // ----------------------------------------------------
  // CATEGORY 11: SPECIAL / TARGETED TRAINING
  // ----------------------------------------------------
  {
    id: "sc-spec-01",
    code: "AITI-SPEC-001",
    title: "ICT for Kids & Teens",
    slug: "ict-for-kids-teens",
    categoryId: "scc-11",
    categoryName: "Special / Targeted Training",
    category: "Special / Targeted Training",
    description: "An engaging, fun tech holiday boot camp for ages 7–16: Scratch block coding, creating video games, basic robotics concepts, typing games, and digital safety.",
    duration: "4 Weeks",
    durationWeeks: 4,
    durationHours: 40,
    fee: 35000,
    feeGHS: 35000,
    trainingFee: 35000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Kids & Teens Innovation Lab)",
    startDate: "2026-09-07",
    endDate: "2026-10-02",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "STEM & Kids Tech Lead",
    availableSeats: 8,
    totalSeats: 20,
    maxSeats: 20,
    maxParticipants: 20,
    enrolledCount: 12,
    certificate: "Young Tech Innovator Certificate",
    certificateType: "Young Tech Innovator Certificate",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Computer appreciation, 10-finger typing racing games, and digital art design in Canva",
      "Week 2: Scratch visual block programming: building animations, interactive stories, and maze games",
      "Week 3: Building a 2D Platformer arcade video game with sound effects and scoring systems",
      "Week 4: Introduction to HTML web page creation, safe web browsing, and final Young Innovators Project Exhibition"
    ],
    learningObjectives: [
      "Ignite a lifelong passion for computer science and logical problem-solving in children",
      "Build interactive 2D arcade video games using Scratch block programming",
      "Type rapidly and navigate computers with creative confidence"
    ],
    entryRequirements: ["Children and teenagers aged 7 to 16 years."],
    scheduleDetails: "Monday to Thursday: 9:00 AM - 12:00 PM"
  },
  {
    id: "sc-spec-02",
    code: "AITI-SPEC-002",
    title: "Tech for Seniors",
    slug: "tech-for-seniors",
    categoryId: "scc-11",
    categoryName: "Special / Targeted Training",
    category: "Special / Targeted Training",
    description: "Patient, zero-stress digital training for elders (50+): smartphone settings, WhatsApp video calls, mobile bank app transfers, online medical consultations, and scam prevention.",
    duration: "2 Weeks",
    durationWeeks: 2,
    durationHours: 20,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Senior Learning Lounge)",
    startDate: "2026-09-07",
    endDate: "2026-09-18",
    instructor: "Mrs. K. O. Balogun",
    instructorName: "Mrs. K. O. Balogun",
    instructorTitle: "Senior Digital Literacy Coach",
    availableSeats: 6,
    totalSeats: 12,
    maxSeats: 12,
    maxParticipants: 12,
    enrolledCount: 6,
    certificate: "Certificate of Digital Independence",
    certificateType: "Certificate of Digital Independence",
    status: "published",
    level: "Beginner",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Oct 5, 2026"],
    courseOutline: [
      "Week 1: Adjusting text size, screen brightness, volume, and contacts navigation on smartphones",
      "Week 1: WhatsApp mastery: sending voice notes, sharing photos, making international family video calls",
      "Week 2: Safe mobile banking: checking balances, making simple utility/airtime transfers, avoiding fraud",
      "Week 2: Watching religious services and news on YouTube, reading e-books, and scam prevention"
    ],
    learningObjectives: [
      "Use smartphones independently without having to ask children or grandchildren for assistance",
      "Connect with distant children and relatives via crystal-clear WhatsApp video calls",
      "Conduct everyday banking transactions safely without falling victim to phone fraudsters"
    ],
    entryRequirements: ["Open to all senior citizens and retirees."],
    scheduleDetails: "Monday to Thursday: 10:00 AM - 12:30 PM (Relaxed Pace)"
  },
  {
    id: "sc-spec-03",
    code: "AITI-SPEC-003",
    title: "Fast-Track Digital Skills",
    slug: "fast-track-digital-skills",
    categoryId: "scc-11",
    categoryName: "Special / Targeted Training",
    category: "Special / Targeted Training",
    description: "An intensive 5-day bootcamp designed for job seekers and NYSC corps members: CV formatting, LinkedIn optimization, essential Excel formulas, and remote work readiness.",
    duration: "1 Week",
    durationWeeks: 1,
    durationHours: 20,
    fee: 25000,
    feeGHS: 25000,
    trainingFee: 25000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Fast-Track Suite), AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-11",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Career & Tech Coach",
    availableSeats: 5,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 10,
    certificate: "Certificate of Practical Competency",
    certificateType: "Certificate of Practical Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 7, 2026", "Sep 21, 2026"],
    courseOutline: [
      "Day 1: Modern ATS-friendly Curriculum Vitae (CV) & Cover Letter design in Word",
      "Day 2: LinkedIn profile transformation: Headline formulas, featured portfolio, and networking scripts",
      "Day 3: Essential workplace Excel: formulas, sorting, filtering, and summary tables required in job tests",
      "Day 4: AI productivity tools: ChatGPT for interview preparation, research, and rapid writing",
      "Day 5: Remote job search platforms (Upwork, RemoteOK, LinkedIn) and virtual interview mastery"
    ],
    learningObjectives: [
      "Craft an ATS-compliant resume that passes corporate screening algorithms",
      "Ace pre-employment computer aptitude and spreadsheet competency tests",
      "Apply for high-paying local and international remote job opportunities"
    ],
    entryRequirements: ["Job seekers, graduates, and NYSC corp members."],
    scheduleDetails: "Monday to Friday: 9:00 AM - 1:00 PM (Intensive)"
  },
  {
    id: "sc-spec-04",
    code: "AITI-SPEC-004",
    title: "Weekend Tech Masterclass",
    slug: "weekend-tech-masterclass",
    categoryId: "scc-11",
    categoryName: "Special / Targeted Training",
    category: "Special / Targeted Training",
    description: "Designed specifically for busy working professionals who cannot attend weekday classes. Covers high-impact practical tech modules held exclusively on Saturdays.",
    duration: "4 Weeks (Saturdays Only)",
    durationWeeks: 4,
    durationHours: 24,
    fee: 40000,
    feeGHS: 40000,
    trainingFee: 40000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "physical",
    mode: "Physical Lab",
    trainingMode: "Physical Lab",
    location: "AITI Tanke Main Campus, Ilorin",
    venue: "Lab Alpha (Executive Suite), AITI Tanke Campus",
    startDate: "2026-09-05",
    endDate: "2026-09-26",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Executive Coach",
    availableSeats: 6,
    totalSeats: 15,
    maxSeats: 15,
    maxParticipants: 15,
    enrolledCount: 9,
    certificate: "Executive Certificate of Competency",
    certificateType: "Executive Certificate of Competency",
    status: "published",
    level: "All Levels",
    featured: true,
    active: true,
    upcomingBatches: ["Sep 5, 2026", "Oct 3, 2026"],
    courseOutline: [
      "Saturday 1: Advanced Excel & Financial Data Analytics for Managers",
      "Saturday 2: AI Tools for 10x Business Productivity & Automation (ChatGPT, Claude, Notion AI)",
      "Saturday 3: Digital Marketing, Meta Ad Campaigns & WhatsApp Business Funnels",
      "Saturday 4: Executive Cyber Defense, Data Privacy & Capstone Technology Presentation"
    ],
    learningObjectives: [
      "Upgrade your career skill set without sacrificing your regular weekday job hours",
      "Network with fellow ambitious corporate professionals and business managers",
      "Master the latest AI, data, and digital marketing tools with hands-on exercises"
    ],
    entryRequirements: ["Working professionals, bankers, civil servants, and business managers."],
    scheduleDetails: "Saturdays only: 10:00 AM - 4:00 PM (Lunch Provided)"
  },
  {
    id: "sc-spec-05",
    code: "AITI-SPEC-005",
    title: "Customized One-on-One Tech Training",
    slug: "customized-one-on-one-tech-training",
    categoryId: "scc-11",
    categoryName: "Special / Targeted Training",
    category: "Special / Targeted Training",
    description: "Private, personalized coaching with a dedicated senior instructor. Learn any tech topic at your own speed, tailored entirely to your personal goals and schedule.",
    duration: "Flexible (1–4 Weeks)",
    durationWeeks: 2,
    durationHours: 20,
    fee: 60000,
    feeGHS: 60000,
    trainingFee: 60000,
    applicationFee: 2000,
    registrationFee: 2000,
    deliveryMode: "hybrid",
    mode: "Private Mentorship",
    trainingMode: "Private Mentorship",
    location: "AITI Tanke Main Campus or Online",
    venue: "Private VIP Coaching Suite, AITI Tanke Campus",
    startDate: "2026-09-07",
    endDate: "2026-09-21",
    instructor: "Dr. O. J. Quadri",
    instructorName: "Dr. O. J. Quadri",
    instructorTitle: "Senior Technology Faculty",
    availableSeats: 3,
    totalSeats: 5,
    maxSeats: 5,
    maxParticipants: 5,
    enrolledCount: 2,
    certificate: "Certificate of Custom Tech Mastery",
    certificateType: "Certificate of Custom Tech Mastery",
    status: "published",
    level: "Customized",
    featured: true,
    active: true,
    upcomingBatches: ["Flexible Enrollment - Start Any Week"],
    courseOutline: [
      "Comprehensive 1-on-1 skills assessment and personalized curriculum design",
      "Dedicated 1-on-1 private laboratory workstation with senior faculty member",
      "Fast-tracked hands-on exercises focused strictly on your business or career project",
      "Flexible schedule tailored to your morning, evening, or weekend availability",
      "Lifetime private mentorship channel and priority technical support"
    ],
    learningObjectives: [
      "Master any specific technology or software suite in half the standard time",
      "Solve your company's immediate technical problems with instructor guidance",
      "Enjoy 100% focused, distraction-free attention tailored to your exact learning speed"
    ],
    entryRequirements: ["Open to anyone seeking private, personalized instruction."],
    scheduleDetails: "Completely Flexible: Choose your own days and hours"
  }
];
